"""Rebuild netlify/offer/fonts.mjs: Carlito (OFL) subset to Latin + Greek, renamed FlowSans.
Needs fontTools and the Carlito TTFs (Debian/Ubuntu: fonts-crosextra-carlito)."""
import base64, os, subprocess, tempfile
from fontTools.ttLib import TTFont

SRC = '/usr/share/fonts/truetype/crosextra/Carlito-{}.ttf'
UNI = 'U+0020-007E,U+00A0-00FF,U+0370-03FF,U+1F00-1FFF,U+2010-2027,U+2030-203A,U+20AC,U+2190-2193,U+2116,U+2122,U+2212,U+2248,U+2260,U+2264,U+2265'
OUT = os.path.join(os.path.dirname(__file__), '..', 'netlify', 'offer', 'fonts.mjs')
lines = ["// Subsets of Carlito (SIL Open Font License 1.1, see OFL.txt), renamed FlowSans as the OFL asks",
         "// for modified versions. Latin + Greek only. Generated by scripts/build_offer_fonts.py.", ""]
with tempfile.TemporaryDirectory() as tmp:
    for w in ['Regular', 'Bold']:
        sub = os.path.join(tmp, f'{w}.ttf')
        subprocess.run(['pyftsubset', SRC.format(w), f'--unicodes={UNI}', '--layout-features=', '--no-hinting',
                        '--desubroutinize', '--name-IDs=*', f'--output-file={sub}'], check=True)
        f = TTFont(sub)
        for rec in f['name'].names:
            if rec.nameID in (1, 3, 4, 6, 16):
                rec.string = {1: 'FlowSans', 16: 'FlowSans', 4: f'FlowSans {w}', 6: f'FlowSans-{w}', 3: f'FlowSans-{w}'}[rec.nameID]
        f.save(sub)
        lines.append(f"export const FLOW_SANS_{w.upper()} = '{base64.b64encode(open(sub, 'rb').read()).decode()}';")
open(OUT, 'w').write('\n'.join(lines) + '\n')
print('wrote', OUT)
