/*
 * Words for the offer PDF and the two emails, in Greek and English.
 * Voice: calm, warm, concrete. Short sentences. The person first, the technology second.
 * Prices live only here and in src/components/flow/offerEngine.js, never on the website.
 */

export const PARTS = {
  dialogos: { name: 'DialogosAI', color: '#6a9bcc', word: { el: 'Λόγος', en: 'Logos' }, role: { el: 'απαντά στους ανθρώπους σας, μέρα και νύχτα', en: 'answers your people, day and night' } },
  praxis: { name: 'PraxisAI', color: '#788c5d', word: { el: 'Πράξη', en: 'Praxis' }, role: { el: 'κρατά τη δουλειά της ομάδας και την κάνει να προχωρά', en: 'holds your team\'s work and moves it forward' } },
  metron: { name: 'MetronAI', color: '#d97757', word: { el: 'Καταγραφή', en: 'Record' }, role: { el: 'καταγράφει και δείχνει τι άλλαξε, σε αριθμούς', en: 'records and shows what changed, in numbers' } },
};

export const COMPANY = {
  el: ['Σημασία-ΑΙ Ι.Κ.Ε. · ΓΕΜΗ 188174403000 · ΑΦΜ 803048250', 'Ναρκίσσου 26, 15452 Παλαιό Ψυχικό · contact@simasiaai.gr · www.simasiaai.gr'],
  en: ['Simasia-AI P.C. · GEMI 188174403000 · VAT no. 803048250', 'Narkissou 26, 15452 Palaio Psychiko, Greece · contact@simasiaai.gr · www.simasiaai.gr'],
};

export const BOOK_URL = 'https://www.simasiaai.gr/go#book';
export const SITE_URL = 'https://www.simasiaai.gr';

export const COPY = {
  el: {
    locale: 'el-GR',
    who: { ngo: 'Οργανισμός, ΜΚΟ ή δομή', med: 'Ιατρείο ή κλινική', sponsor: 'Χορηγός' },
    by: 'της SimasiaAI',
    label: 'ΠΡΟΣΦΟΡΑ',
    ref: 'Αρ.',
    date: 'Ημερομηνία',
    valid: 'Ισχύει έως',
    title: (org) => `Η προσφορά σας${org ? `, ${org}` : ''}`,
    forLine: (name, who) => `Για ${name} · ${who}`,
    intro: {
      ngo: 'Μας είπατε πώς κυλά η μέρα σας. Από τις απαντήσεις σας σχεδιάσατε το fλow που σας ταιριάζει. Εδώ είναι όλο, με την τιμή του, χωρίς ψιλά γράμματα.',
      med: 'Μας είπατε πώς κυλά η μέρα στο ιατρείο σας. Από τις απαντήσεις σας σχεδιάσατε το fλow που σας ταιριάζει. Εδώ είναι όλο, με την τιμή του, χωρίς ψιλά γράμματα.',
      sponsor: 'Μας είπατε τι θέλετε να στηρίξετε. Εδώ είναι η στήριξη που σχεδιάσατε, με το κόστος της και με το αποτέλεσμα που θα βλέπετε κάθε τρίμηνο.',
    },
    timeTitle: 'Ο χρόνος που επιστρέφει',
    timeHours: (h) => `≈ ${h} ώρες τον μήνα`,
    timeHoursSub: 'πίσω στην ομάδα σας, για ανθρώπους αντί για επαναλήψεις',
    timeDays: (d) => `≈ ${d} εργάσιμες μέρες τον χρόνο`,
    timeAppts: (n) => `+ ${n} ραντεβού τον μήνα από κλήσεις που σήμερα χάνονται`,
    timeNote: 'Εκτίμηση από τις απαντήσεις σας. Τη μετράμε μαζί σας κάθε μήνα στο MetronAI.',
    impactTitle: 'Ο αντίκτυπός σας',
    impactPeople: (n) => `${n} άνθρωποι τον χρόνο`,
    impactOrgs: (n) => `${n} οργανισμοί`,
    yourFlow: 'Το fλow σας',
    included: 'Περιλαμβάνεται',
    yourOptions: 'Όσα προσθέσατε',
    freeWithTwo: 'Δωρεάν με 2+ μέρη',
    quoteTitle: 'Κατόπιν προσφοράς',
    quoteNote: 'Τα κοστολογούμε μαζί σας στη συνάντηση των 30 λεπτών.',
    customTitle: 'Δικά σας αιτήματα, θα τιμολογηθούν',
    customNote: 'Τα κοστολογούμε μαζί σας και τα προσθέτουμε στην τελική πρόταση.',
    perMonth: '/μήνα',
    oneOff: 'εφάπαξ',
    atCost: 'φιλοξενία και χρήση AI στο κόστος τους',
    priceTitle: 'Τι επενδύετε',
    monthly: 'Μηνιαία συνδρομή',
    setup: 'Ένταξη στη ροή',
    setupSub: 'εφάπαξ: στήσιμο, βάση γνώσης, εκπαίδευση',
    firstYear: 'Πρώτος χρόνος, συνολικά',
    from: 'από',
    saving: (m, s) => `Επειδή τα μέρη δουλεύουν μαζί, εξοικονομείτε ${m} τον μήνα και ${s} στην ένταξη.`,
    network: 'Για δίκτυα και πολλές δομές η τιμή είναι η αφετηρία. Την προσαρμόζουμε μαζί σας.',
    medTier: (name) => `Επίπεδο «${name}»`,
    medAnnual: 'Με ετήσια συνδρομή',
    medAnnualSub: 'η ένταξη είναι δωρεάν',
    medMonthly: 'Με μηνιαία συνδρομή',
    medMonthlySub: (s) => `+ ${s} ένταξη, εφάπαξ`,
    medRec: 'Προτείνουμε',
    medCustom: 'Για 6+ γιατρούς ή πολλά σημεία η τιμή είναι η αφετηρία. Την προσαρμόζουμε μαζί σας.',
    medExtra: (s) => `+ ${s} εφάπαξ για το ελληνικό μοντέλο σε υποδομή ΕΕ`,
    spTotal: (y) => `Συνολικό κόστος, ${y === 1 ? '1 χρόνος' : `${y} χρόνια`}`,
    spPerPerson: 'ανά άνθρωπο που φτάνει, τον χρόνο',
    spOrgs: 'Οργανισμοί',
    spBreak: (setup, monthly, impact) => `Ένταξη ${setup} · Συνδρομή ${monthly}/μήνα · Αναφορές αντίκτυπου ${impact}`,
    spCause: 'Τομέας',
    spWhat: 'Τι παίρνετε',
    spList: ['Αναφορά αντίκτυπου κάθε τρίμηνο: πόσοι ενημερώθηκαν, τι ρώτησαν, τι έλειπε', 'Φάκελος έτοιμος για δημοσιοποίηση (ΣΦΕΕ / EFPIA)', 'Ο οργανισμός ελέγχει το περιεχόμενο· ο χορηγός δεν επηρεάζει απαντήσεις', 'Καμία ιατρική συμβουλή, καμία προώθηση προϊόντος', 'Σύμφωνο με EU AI Act και GDPR, φιλοξενία στην ΕΕ', '«Με την υποστήριξη του …» σε κάθε συνομιλία'],
    riskTitle: 'Ξεκινήστε χωρίς ρίσκο',
    trial: {
      ngo: ['Δοκιμή 60 ημερών με 199 €', 'Με τα δικά σας δεδομένα και τους δικούς σας ανθρώπους. Αν συνεχίσετε, τα 199 € αφαιρούνται από την ένταξη.'],
      med: ['Δοκιμή 30 ημερών με 199 €', 'Live σε 48 ώρες, αλλιώς δωρεάν. Βλέπετε το fλow να δουλεύει στο ιατρείο σας πριν δεσμευτείτε.'],
    },
    guarantee: {
      ngo: ['Εγγύηση ακρίβειας', 'Αν στις 60 μέρες δεν απαντά σωστά στο 90% των ερωτήσεων που συμφωνήσαμε, η συνδρομή είναι δωρεάν ώσπου να το πετύχει.'],
      med: ['Τεστ αποδοχής', 'Με 50 πραγματικές ερωτήσεις, μπροστά σας. Αν δεν φτάσει το 90% ακρίβεια, δεν πληρώνετε.'],
      sponsor: ['Μετριέται κάθε μήνα', 'Βλέπετε πόσους ανθρώπους έφτασε, πριν το δει οποιοσδήποτε άλλος.'],
    },
    person: ['Ένας άνθρωπος δίπλα σας', 'Ο project manager σας, από το πρώτο τηλεφώνημα μέχρι πολύ μετά το live.'],
    compliance: ['Συμμόρφωση πρώτα', 'Νομικός έλεγχος σε κάθε έργο από συνεργαζόμενη νομική εταιρεία.'],
    stackTitle: 'Μαζί με τη συνδρομή, χωρίς επιπλέον χρέωση',
    stack: [
      ['Προσωπικός project manager, ένας άνθρωπος από την πρώτη μέρα', 900],
      ['Τακτοποιούμε τα αρχεία σας και φτιάχνουμε τη βάση γνώσης, χωρίς δική σας δουλειά', 350],
      ['Τεστ αποδοχής σε 50 ερωτήσεις και απαντήσεις, πριν βγει στους ανθρώπους σας', 400],
      ['Εκπαίδευση της ομάδας: οδηγός και video στη γλώσσα της', 150],
      ['QR και έντυπα για να το βρίσκουν οι άνθρωποί σας', 100],
      ['Πάντα τα νεότερα και ισχυρότερα μοντέλα AI', 400],
      ['Μηνιαίες συναντήσεις με την ομάδα μας', 600],
      ['Επείγουσες διορθώσεις μέσα σε 24 ώρες', 300],
      ['Υποστήριξη μέσω chat, 24/7', 250],
      ['Αναφορά για όσα ζήτησαν οι άνθρωποί σας και δεν βρήκαν', 500],
    ],
    stackWorth: 'Αξία',
    stackYou: 'Για εσάς',
    proofTitle: 'Ήδη σε ροή',
    proof: ['Κάπα3 · η Μυρτώ στηρίζει ανθρώπους με καρκίνο και τις οικογένειές τους', 'ΠΟΑμΣΚΠ · το ΣΚΠ-i απαντά σε ανθρώπους με σκλήρυνση κατά πλάκας, 24 ώρες το 24ωρο', 'Ήρωες της BPAN · το BPAN Companion στηρίζει οικογένειες με σπάνιο νόσημα'],
    funding: 'Συχνά δεν το πληρώνει ο οργανισμός. Σας βοηθάμε να το εντάξετε σε χορηγία, CSR ή ευρωπαϊκό πρόγραμμα.',
    toldTitle: 'Τι μας είπατε',
    nextTitle: 'Τα επόμενα βήματα',
    next: {
      ngo: ['Κλείστε 30 λεπτά μαζί μας ή απαντήστε «Ναι» σε αυτό το email.', 'Ένα εργαστήριο 45 λεπτών. Τα υπόλοιπα τα στήνουμε εμείς, με τα δικά σας έγγραφα.', 'Το DialogosAI απαντά από τις πρώτες 48 ώρες. Η δοκιμή σας ξεκινά.'],
      med: ['Κλείστε 30 λεπτά μαζί μας ή απαντήστε «Ναι» σε αυτό το email.', 'Μας στέλνετε ωράριο, τιμοκατάλογο και ό,τι ρωτούν οι ασθενείς. Στήνουμε εμείς.', 'Live σε 48 ώρες. Η δοκιμή σας ξεκινά.'],
      sponsor: ['Κλείστε 30 λεπτά μαζί μας ή απαντήστε «Ναι» σε αυτό το email.', 'Μαζί διαλέγουμε τον οργανισμό ή τους οργανισμούς και τον στόχο.', 'Η πρώτη αναφορά αντίκτυπου έρχεται στο τέλος του πρώτου τριμήνου.'],
    },
    cta: 'Κλείστε 30 λεπτά',
    ctaAlt: 'ή γράψτε μας στο contact@simasiaai.gr',
    fine: 'Τιμές χωρίς ΦΠΑ. Φιλοξενία και χρήση AI στο κόστος τους. Η προσφορά ισχύει 30 ημέρες.',
    page: (a, b) => `${a} / ${b}`,
    fileName: (ref) => `SimasiaAI-flow-prosfora-${ref}.pdf`,
    // email to the visitor
    mail: {
      subject: (org) => `Η προσφορά σας για το fλow${org ? `, ${org}` : ''}`,
      preheader: 'Όσα διαλέξατε, με τιμή και δοκιμή χωρίς ρίσκο. Όλα στο PDF.',
      hello: (name) => `Γεια σας ${name},`,
      p1: {
        ngo: 'Ευχαριστούμε που μας είπατε για τη μέρα σας. Από τις απαντήσεις σας σχεδιάσατε ένα fλow στα μέτρα σας. Η προσφορά σας είναι στο PDF που επισυνάπτουμε, με κάθε επιλογή και την τιμή της.',
        med: 'Ευχαριστούμε που μας είπατε για τη μέρα στο ιατρείο σας. Από τις απαντήσεις σας σχεδιάσατε ένα fλow στα μέτρα σας. Η προσφορά σας είναι στο PDF που επισυνάπτουμε, με κάθε επιλογή και την τιμή της.',
        sponsor: 'Ευχαριστούμε που θέλετε να στηρίξετε ανθρώπους που το χρειάζονται. Η πρόταση που σχεδιάσατε είναι στο PDF που επισυνάπτουμε, με το κόστος και το αποτέλεσμα που θα βλέπετε κάθε τρίμηνο.',
      },
      glance: 'Με μια ματιά',
      parts: 'Το fλow σας',
      time: (h) => `Περίπου ${h} ώρες τον μήνα επιστρέφουν στην ομάδα σας.`,
      p2: {
        ngo: 'Δεν ρισκάρετε τίποτα: ξεκινάτε με δοκιμή 60 ημερών με 199 €, που αφαιρούνται από την ένταξη, και με εγγύηση ακρίβειας. Στήνουμε εμείς, με τα δικά σας έγγραφα, και ένας άνθρωπος μένει δίπλα σας σε κάθε βήμα.',
        med: 'Δεν ρισκάρετε τίποτα: δοκιμή 30 ημερών με 199 €, live σε 48 ώρες, αλλιώς δωρεάν. Στήνουμε εμείς, από τις πληροφορίες του ιατρείου σας.',
        sponsor: 'Η στήριξή σας μετριέται κάθε μήνα και φτάνει σε ανθρώπους, χωρίς προώθηση προϊόντος και με νομικό έλεγχο σε κάθε έργο.',
      },
      proof: 'Το fλow λειτουργεί ήδη για το Κάπα3, την ΠΟΑμΣΚΠ και τους Ήρωες της BPAN.',
      p3: 'Το επόμενο βήμα είναι μια συζήτηση 30 λεπτών. Ή απλώς απαντήστε σε αυτό το email με ένα «Ναι» και σας καλούμε εμείς.',
      cta: 'Κλείστε 30 λεπτά',
      ps: 'Υ.Γ. Η προσφορά ισχύει 30 ημέρες.',
      psFunding: 'Υ.Γ. Η προσφορά ισχύει 30 ημέρες. Αν δεν θέλετε να το πληρώσει ο οργανισμός, σας βοηθάμε να βρείτε χορηγό, CSR ή ευρωπαϊκό πρόγραμμα.',
      sign: ['Με εκτίμηση,', 'Δημήτρης Παπαδάκης', 'Co-founder & Head of Sales, SimasiaAI'],
      footer: 'Λάβατε αυτό το email επειδή ζητήσατε προσφορά στο simasiaai.gr. Αν δεν το ζητήσατε εσείς, απλώς αγνοήστε το.',
    },
  },

  en: {
    locale: 'en-IE',
    who: { ngo: 'Organisation, NGO or care service', med: 'Practice or clinic', sponsor: 'Sponsor' },
    by: 'by SimasiaAI',
    label: 'OFFER',
    ref: 'No.',
    date: 'Date',
    valid: 'Valid until',
    title: (org) => `Your offer${org ? `, ${org}` : ''}`,
    forLine: (name, who) => `For ${name} · ${who}`,
    intro: {
      ngo: 'You told us how your day runs. From your answers you designed the fλow that fits you. Here it is in full, with its price and no small print.',
      med: 'You told us how the day runs at your practice. From your answers you designed the fλow that fits you. Here it is in full, with its price and no small print.',
      sponsor: 'You told us what you want to support. Here is the support you designed, with its cost and the result you will see every quarter.',
    },
    timeTitle: 'The time that comes back',
    timeHours: (h) => `≈ ${h} hours a month`,
    timeHoursSub: 'back to your team, for people instead of repetition',
    timeDays: (d) => `≈ ${d} working days a year`,
    timeAppts: (n) => `+ ${n} appointments a month from calls lost today`,
    timeNote: 'An estimate from your answers. We measure it with you every month in MetronAI.',
    impactTitle: 'Your impact',
    impactPeople: (n) => `${n} people a year`,
    impactOrgs: (n) => `${n} organisations`,
    yourFlow: 'Your fλow',
    included: 'Included',
    yourOptions: 'What you added',
    freeWithTwo: 'Free with 2+ parts',
    quoteTitle: 'On request',
    quoteNote: 'We price these with you in the 30-minute call.',
    customTitle: 'Your own requests, to be priced',
    customNote: 'We price them with you and add them to the final proposal.',
    perMonth: '/month',
    oneOff: 'one-off',
    atCost: 'hosting and AI usage at cost',
    priceTitle: 'Your investment',
    monthly: 'Monthly subscription',
    setup: 'Onboarding into the flow',
    setupSub: 'one-off: set-up, knowledge base, training',
    firstYear: 'First year, in total',
    from: 'from',
    saving: (m, s) => `Because the parts work together, you save ${m} a month and ${s} on onboarding.`,
    network: 'For networks and several services the price is the starting point. We fit it to you.',
    medTier: (name) => `Level "${name}"`,
    medAnnual: 'With annual billing',
    medAnnualSub: 'onboarding is free',
    medMonthly: 'With monthly billing',
    medMonthlySub: (s) => `+ ${s} onboarding, one-off`,
    medRec: 'We suggest',
    medCustom: 'For 6+ doctors or several sites the price is the starting point. We fit it to you.',
    medExtra: (s) => `+ ${s} one-off for the Greek model on EU infrastructure`,
    spTotal: (y) => `Total cost, ${y === 1 ? '1 year' : `${y} years`}`,
    spPerPerson: 'per person reached, per year',
    spOrgs: 'Organisations',
    spBreak: (setup, monthly, impact) => `Onboarding ${setup} · Subscription ${monthly}/month · Impact reports ${impact}`,
    spCause: 'Area',
    spWhat: 'What you get',
    spList: ['A quarterly impact report: how many were informed, what they asked, what was missing', 'A disclosure-ready file (SFEE / EFPIA)', 'The organisation controls content; the sponsor never shapes answers', 'No medical advice, no product promotion', 'EU AI Act and GDPR compliant, hosted in the EU', '"Supported by …" in every conversation'],
    riskTitle: 'Start with no risk',
    trial: {
      ngo: ['60-day pilot for €199', 'With your own data and your own people. If you continue, the €199 is credited against onboarding.'],
      med: ['30-day trial for €199', 'Live in 48 hours, or free. You see fλow working at your practice before you commit.'],
    },
    guarantee: {
      ngo: ['Accuracy guarantee', 'If at 60 days it does not answer 90% of the questions we agreed correctly, the subscription is free until it does.'],
      med: ['Acceptance test', 'With 50 real questions, in front of you. If it does not reach 90% accuracy, you don\'t pay.'],
      sponsor: ['Measured every month', 'You see how many people it reached before anyone else does.'],
    },
    person: ['One person beside you', 'Your project manager, from the first call to well after launch.'],
    compliance: ['Compliance first', 'A partner law firm reviews every project.'],
    stackTitle: 'Included with your subscription, at no extra cost',
    stack: [
      ['A personal project manager, one person from day one', 900],
      ['We organise your files and build your knowledge base, with no work on your side', 350],
      ['Acceptance test on 50 questions and answers, before it reaches your people', 400],
      ['Team training: a guide and video in their language', 150],
      ['QR codes and print material so your people find it', 100],
      ['Always the newest, strongest AI models', 400],
      ['Monthly meetings with our team', 600],
      ['Urgent fixes within 24 hours', 300],
      ['Chat support, 24/7', 250],
      ['A report on what your people asked for and did not find', 500],
    ],
    stackWorth: 'Worth',
    stackYou: 'For you',
    proofTitle: 'Already in flow',
    proof: ['Kapa3 · Myrto supports people with cancer and their families', 'POAmSKP · ΣΚΠ-i answers people with multiple sclerosis, around the clock', 'BPAN Heroes · BPAN Companion supports families living with a rare disease'],
    funding: 'Often the organisation doesn\'t pay. We help you fit it into a sponsorship, CSR or an EU programme.',
    toldTitle: 'What you told us',
    nextTitle: 'Next steps',
    next: {
      ngo: ['Book 30 minutes with us, or reply "Yes" to this email.', 'One 45-minute workshop. We set up the rest, from your own documents.', 'DialogosAI answers within the first 48 hours. Your pilot begins.'],
      med: ['Book 30 minutes with us, or reply "Yes" to this email.', 'You send us your hours, price list and what patients ask. We set it up.', 'Live in 48 hours. Your trial begins.'],
      sponsor: ['Book 30 minutes with us, or reply "Yes" to this email.', 'Together we choose the organisation or organisations and the goal.', 'The first impact report arrives at the end of the first quarter.'],
    },
    cta: 'Book 30 minutes',
    ctaAlt: 'or write to contact@simasiaai.gr',
    fine: 'Prices exclude VAT. Hosting and AI usage at cost. This offer is valid for 30 days.',
    page: (a, b) => `${a} / ${b}`,
    fileName: (ref) => `SimasiaAI-flow-offer-${ref}.pdf`,
    mail: {
      subject: (org) => `Your fλow offer${org ? `, ${org}` : ''}`,
      preheader: 'Everything you chose, with the price and a no-risk start. All in the PDF.',
      hello: (name) => `Hello ${name},`,
      p1: {
        ngo: 'Thank you for telling us about your day. From your answers you designed a fλow made to measure. Your offer is in the attached PDF, with every choice and its price.',
        med: 'Thank you for telling us about the day at your practice. From your answers you designed a fλow made to measure. Your offer is in the attached PDF, with every choice and its price.',
        sponsor: 'Thank you for wanting to support people who need it. The proposal you designed is in the attached PDF, with its cost and the result you will see every quarter.',
      },
      glance: 'At a glance',
      parts: 'Your fλow',
      time: (h) => `About ${h} hours a month come back to your team.`,
      p2: {
        ngo: 'You risk nothing: you start with a 60-day pilot for €199, credited against onboarding, and an accuracy guarantee. We set it up from your own documents, and one person stays beside you at every step.',
        med: 'You risk nothing: a 30-day trial for €199, live in 48 hours, or free. We set it up from your practice\'s information.',
        sponsor: 'Your support is measured every month and reaches people, with no product promotion and a legal review on every project.',
      },
      proof: 'fλow already runs for Kapa3, POAmSKP and BPAN Heroes.',
      p3: 'The next step is a 30-minute conversation. Or simply reply "Yes" to this email and we will call you.',
      cta: 'Book 30 minutes',
      ps: 'P.S. This offer is valid for 30 days.',
      psFunding: 'P.S. This offer is valid for 30 days. If you would rather the organisation didn\'t pay, we help you find a sponsor, CSR or an EU programme.',
      sign: ['Kind regards,', 'Dimitris Papadakis', 'Co-founder & Head of Sales, SimasiaAI'],
      footer: 'You received this email because you asked for an offer on simasiaai.gr. If it wasn\'t you, simply ignore it.',
    },
  },
};
