// Copy for /flow/build ("Φτιάξτε το fλow σας"). Each audience is spoken to in its own terms:
// NGOs: people supported, sponsors, calm teams. Clinics: bookings, missed calls, time.
// Sponsors: reach, cost per person, compliance, disclosure.

export const builderCopy = {
  el: {
    title: 'Φτιάξτε το fλow σας',
    lead: 'Διαλέξτε ποιος είστε και τι θέλετε να κυλά πιο ήσυχα. Η ροή και η τιμή αλλάζουν μπροστά σας. Στο τέλος παίρνετε την προσφορά σας.',
    steps: ['Ποιος είστε', 'Πόσους στηρίζετε', 'Τι θέλετε να ρέει', 'Η μέρα σας σήμερα', 'Η προσφορά σας'],
    who: {
      ngo: { name: 'Οργανισμός ή ΜΚΟ', line: 'Σύλλογοι ασθενών, δομές ΑμεΑ, ομοσπονδίες', pitch: 'Για εσάς το fλow είναι πρώτα ο πίνακας Insights: δείχνει σε ομάδα και χορηγούς τι χρειάζονται οι άνθρωποί σας.' },
      med: { name: 'Ιατρείο ή κλινική', line: 'Γιατροί, πολυϊατρεία, διαγνωστικά', pitch: 'Για εσάς το fλow είναι πρώτα ο PraxisAI: κάθε τηλέφωνο και μήνυμα γίνεται ραντεβού ή καρτέλα, ακόμα κι όταν εξετάζετε.' },
      sponsor: { name: 'Χορηγός', line: 'Φαρμακευτικές, ιδρύματα, εταιρείες με CSR', pitch: 'Για εσάς το fλow είναι στήριξη που μετριέται: πόσους ανθρώπους έφτασε, με ποιο κόστος ανά άνθρωπο, έτοιμο για δημοσιοποίηση.' },
    },
    size: {
      ngo: 'Πόσους ανθρώπους στηρίζετε τον χρόνο;',
      med: 'Πόσοι γιατροί δουλεύουν μαζί σας;',
      sponsor: ['Πόσους οργανισμούς θέλετε να στηρίξετε;', 'Πόσους ανθρώπους φτάνουν τον χρόνο;', 'Για πόσο καιρό;', 'Σε ποιον τομέα;'],
      years: ['1 χρόνο', '2 χρόνια'],
      people: 'άνθρωποι τον χρόνο',
    },
    groups: { logos: 'DialogosAI · μιλά', praxis: 'PraxisAI · θυμάται', insights: 'Insights · δείχνει', extra: 'Επιλογές για φορείς' },
    included: 'Περιλαμβάνεται',
    always: 'Πάντα μέσα',
    soon: 'Σύντομα',
    atCost: 'φιλοξενία στο κόστος',
    recommended: 'Προτείνεται',
    perMonth: '/μήνα',
    setup: 'εφάπαξ',
    billing: ['Μηνιαία', 'Ετήσια'],
    annualNote: 'Με ετήσια συνδρομή η ένταξη είναι δωρεάν.',
    pains: {
      title: 'Πού χάνεται ο χρόνος σας σήμερα;',
      hint: 'Πατήστε όσα ισχύουν. Θα φανούν αριστερά στη ροή.',
      ngo: ['Τηλέφωνα από οικογένειες', 'Σημειώσεις σε χαρτιά και Excel', 'Ξεχασμένες λήξεις', 'Αναφορές για χορηγούς', 'Ερωτήσεις για δικαιώματα', 'Μηνύματα εκτός ωραρίου'],
      med: ['Αναπάντητες κλήσεις', 'Ακυρώσεις χωρίς αντικατάσταση', 'Ερωτήσεις για τιμές και ΕΟΠΥΥ', 'Ξεχασμένοι επανέλεγχοι', 'Ιστορικό στην αίθουσα αναμονής', 'Μηνύματα σε 4 εφαρμογές'],
      sponsor: ['Δεν ξέρουμε πόσους φτάσαμε', 'Αναφορές που αργούν', 'Φόβος για συμμόρφωση', 'Χορηγίες χωρίς διάρκεια', 'Δύσκολη δημοσιοποίηση', 'Κανείς δεν βλέπει το αποτέλεσμα'],
      q2: { ngo: 'Πόσα τηλέφωνα και μηνύματα δέχεστε τη μέρα;', med: 'Πόσες κλήσεις χάνετε τη μέρα;', sponsor: 'Τι θέλετε να δείχνει η αναφορά;' },
      a2: { ngo: ['Λιγότερα από 10', '10 – 30', 'Πάνω από 30'], med: ['1 – 2', '3 – 5', 'Πάνω από 5'], sponsor: ['Ανθρώπους που ενημερώθηκαν', 'Ανάγκες χωρίς απάντηση', 'Γεωγραφική κάλυψη', 'Ικανοποίηση'] },
      q3: 'Πότε θα θέλατε να ξεκινήσετε;',
      a3: ['Τώρα', 'Σε 1 – 3 μήνες', 'Ψάχνουμε χρηματοδότηση'],
    },
    graphic: { today: 'Σήμερα', withFlow: 'Με fλow', empty: 'Επιλέξτε τι θέλετε να ρέει', aria: 'Η ροή σας: αριστερά όσα σας δυσκολεύουν σήμερα, στη μέση το fλow, δεξιά όσα επιλέξατε.' },
    offer: {
      title: 'Η προσφορά σας',
      plan: 'Πακέτο',
      monthly: 'Μηνιαία',
      setup: 'Ένταξη στη ροή',
      firstYear: 'Πρώτος χρόνος',
      from: 'από',
      worth: 'Αξία αν τα αγοράζατε χωριστά',
      pilot: 'Ή ξεκινήστε με δοκιμή 60 ημερών με 490 €, που αφαιρούνται από την ένταξη.',
      guarantee: 'Εγγύηση: αν στις 60 μέρες δεν απαντά σωστά στο 90% των ερωτήσεων που συμφωνήσαμε, η συνδρομή είναι δωρεάν ώσπου να το πετύχει.',
      guaranteeMed: 'Live σε 48 ώρες, αλλιώς δωρεάν. Αν δεν φτάσει το 90% ακρίβεια στο τεστ αποδοχής, δεν πληρώνετε.',
      funding: 'Συχνά δεν το πληρώνει ο οργανισμός. Σας βοηθάμε να βρείτε χορηγό, CSR ή ευρωπαϊκό πρόγραμμα.',
      custom: 'Για αυτό το μέγεθος φτιάχνουμε προσφορά μαζί σας. Η τιμή είναι η αφετηρία.',
      total: 'Συνολικό κόστος',
      orgs: 'Οργανισμοί',
      perPerson: 'ανά άνθρωπο που φτάνει, τον χρόνο',
      sponsorWhat: 'Τι παίρνετε',
      sponsorList: ['Αναφορά αντίκτυπου κάθε τρίμηνο', 'Φάκελος έτοιμος για δημοσιοποίηση (ΣΦΕΕ / EFPIA)', 'Ο οργανισμός ελέγχει το περιεχόμενο· ο χορηγός δεν επηρεάζει απαντήσεις', 'Καμία ιατρική συμβουλή, καμία προώθηση προϊόντος', 'Σύμφωνο με EU AI Act και GDPR, φιλοξενία στην ΕΕ', '«Με την υποστήριξη του …» σε κάθε συνομιλία'],
      oneNumber: 'Ο αριθμός που θα βλέπετε κάθε μήνα',
      oneNumberText: 'Ερωτήσεις που απαντήθηκαν από εγκεκριμένες πηγές',
      proof: 'Το ΣΚΠ-i της ΠΟΑμΣΚΠ λειτουργεί ήδη με την υποστήριξη φαρμακευτικών εταιρειών.',
      note: 'Τιμές χωρίς ΦΠΑ. Φιλοξενία και χρήση AI στο κόστος τους. Η προσφορά ισχύει 30 μέρες.',
    },
    contact: {
      title: 'Στείλτε μας τη ροή σας',
      lead: 'Σας απαντάμε μέσα σε μία εργάσιμη με την προσφορά σε PDF και μια πρόταση για 30 λεπτά.',
      name: 'Όνομα', org: 'Οργανισμός', email: 'Email', phone: 'Τηλέφωνο (προαιρετικό)',
      consent: 'Συμφωνώ να επικοινωνήσει μαζί μου η SimasiaAI για αυτή την προσφορά.',
      send: 'Στείλτε την προσφορά',
      print: 'Κατεβάστε την ως PDF',
      printSponsor: 'Κατεβάστε το one-pager',
      sending: 'Αποστολή…',
      sent: 'Τη λάβαμε. Θα σας γράψουμε μέσα σε μία εργάσιμη.',
      fallback: 'Η αποστολή δεν έγινε από εδώ. Ανοίξτε το email σας με την προσφορά έτοιμη:',
      fallbackLink: 'Άνοιγμα email',
      required: 'Συμπληρώστε όνομα, email και τη συγκατάθεση.',
    },
    summaryBar: 'Δείτε την προσφορά',
  },
  en: {
    title: 'Build your fλow',
    lead: 'Choose who you are and what you want to run more quietly. The flow and the price change in front of you. At the end you get your offer.',
    steps: ['Who you are', 'How many you support', 'What should flow', 'Your day today', 'Your offer'],
    who: {
      ngo: { name: 'Organisation or NGO', line: 'Patient groups, disability services, federations', pitch: 'For you, fλow is first the Insights dashboard: it shows your team and sponsors what your people need.' },
      med: { name: 'Practice or clinic', line: 'Doctors, polyclinics, diagnostics', pitch: 'For you, fλow is first PraxisAI: every call and message becomes a booking or a patient card, even while you examine.' },
      sponsor: { name: 'Sponsor', line: 'Pharma, foundations, companies with CSR', pitch: 'For you, fλow is support you can measure: how many people it reached, at what cost per person, ready for disclosure.' },
    },
    size: {
      ngo: 'How many people do you support a year?',
      med: 'How many doctors work with you?',
      sponsor: ['How many organisations do you want to support?', 'How many people do they reach a year?', 'For how long?', 'In which area?'],
      years: ['1 year', '2 years'],
      people: 'people a year',
    },
    groups: { logos: 'DialogosAI · talks', praxis: 'PraxisAI · remembers', insights: 'Insights · shows', extra: 'Options for public bodies' },
    included: 'Included', always: 'Always in', soon: 'Soon', atCost: 'hosting at cost', recommended: 'Recommended',
    perMonth: '/month', setup: 'one-off', billing: ['Monthly', 'Annual'], annualNote: 'With annual billing, onboarding is free.',
    pains: {
      title: 'Where does your time go today?',
      hint: 'Tap all that apply. They appear on the left of the flow.',
      ngo: ['Calls from families', 'Notes on paper and Excel', 'Missed expiry dates', 'Reports for sponsors', 'Questions about rights', 'Messages after hours'],
      med: ['Missed calls', 'Cancellations left empty', 'Questions on prices and insurance', 'Forgotten check-ups', 'History filled in the waiting room', 'Messages in 4 apps'],
      sponsor: ['We don\'t know how many we reached', 'Reports arrive late', 'Compliance worries', 'Sponsorships without continuity', 'Hard to disclose', 'Nobody sees the result'],
      q2: { ngo: 'How many calls and messages a day?', med: 'How many calls do you miss a day?', sponsor: 'What should the report show?' },
      a2: { ngo: ['Fewer than 10', '10 – 30', 'More than 30'], med: ['1 – 2', '3 – 5', 'More than 5'], sponsor: ['People informed', 'Unmet needs', 'Geographic reach', 'Satisfaction'] },
      q3: 'When would you like to start?',
      a3: ['Now', 'In 1 – 3 months', 'Looking for funding'],
    },
    graphic: { today: 'Today', withFlow: 'With fλow', empty: 'Choose what should flow', aria: 'Your flow: on the left what is hard today, fλow in the middle, on the right what you chose.' },
    offer: {
      title: 'Your offer', plan: 'Plan', monthly: 'Monthly', setup: 'Onboarding into the flow', firstYear: 'First year', from: 'from',
      worth: 'Value if bought separately',
      pilot: 'Or start with a 60-day pilot for €490, credited against onboarding.',
      guarantee: 'Guarantee: if at 60 days it doesn\'t answer 90% of our agreed questions correctly, the subscription is free until it does.',
      guaranteeMed: 'Live in 48 hours, or free. If it doesn\'t reach 90% accuracy in the acceptance test, you don\'t pay.',
      funding: 'Often the organisation doesn\'t pay. We help you find a sponsor, CSR or EU programme.',
      custom: 'For this size we build the offer with you. The price is the starting point.',
      total: 'Total cost', orgs: 'Organisations', perPerson: 'per person reached, per year',
      sponsorWhat: 'What you get',
      sponsorList: ['Quarterly impact report', 'Disclosure-ready file (SFEE / EFPIA)', 'The organisation controls content; the sponsor never shapes answers', 'No medical advice, no product promotion', 'EU AI Act and GDPR compliant, hosted in the EU', '"Supported by …" in every conversation'],
      oneNumber: 'The number you will see every month', oneNumberText: 'Questions answered from approved sources',
      proof: 'ΣΚΠ-i by POAmSKP already runs with the support of pharmaceutical companies.',
      note: 'Prices exclude VAT. Hosting and AI usage at cost. Offer valid for 30 days.',
    },
    contact: {
      title: 'Send us your flow', lead: 'We reply within one working day with the offer as a PDF and a 30-minute slot.',
      name: 'Name', org: 'Organisation', email: 'Email', phone: 'Phone (optional)',
      consent: 'I agree that SimasiaAI may contact me about this offer.',
      send: 'Send the offer', print: 'Download as PDF', printSponsor: 'Download the one-pager', sending: 'Sending…',
      sent: 'Received. We will write to you within one working day.',
      fallback: 'It could not be sent from here. Open your email with the offer ready:', fallbackLink: 'Open email',
      required: 'Please fill in name, email and consent.',
    },
    summaryBar: 'See the offer',
  },
};
