// Copy for /flow/build ("Φτιάξτε το fλow σας"). Each audience is spoken to in its own terms:
// NGOs: people supported, sponsors, calm teams. Clinics: bookings, missed calls, time.
// Sponsors: reach, cost per person, compliance, disclosure.

export const builderCopy = {
  el: {
    title: 'Φτιάξτε το fλow σας',
    lead: 'Διαλέξτε ποιος είστε και τι θέλετε να κυλά πιο ήσυχα. Η ροή και η τιμή αλλάζουν μπροστά σας. Στο τέλος παίρνετε την προσφορά σας.',
    steps: ['Ποιος είστε', 'Πόσους στηρίζετε', 'Τι θέλετε να ρέει', 'Η μέρα σας σήμερα', 'Η προσφορά σας'],
    who: {
      ngo: { name: 'Οργανισμός ή ΜΚΟ', line: 'Σύλλογοι ασθενών, δομές ΑμεΑ, ομοσπονδίες', pitch: 'Για εσάς το fλow ξεκινά από το DialogosAI και το MetronAI: απαντήσεις στους ανθρώπους σας και δεδομένα που δείχνουν σε ομάδα και χορηγούς τι χρειάζονται.' },
      med: { name: 'Ιατρείο ή κλινική', line: 'Γιατροί, πολυϊατρεία, διαγνωστικά', pitch: 'Για εσάς το fλow είναι πρώτα το PraxisAI: κάθε τηλέφωνο και μήνυμα γίνεται ραντεβού ή καρτέλα, ακόμα κι όταν εξετάζετε.' },
      sponsor: { name: 'Χορηγός', line: 'Φαρμακευτικές, ιδρύματα, εταιρείες με CSR', pitch: 'Για εσάς το fλow είναι στήριξη που μετριέται: πόσους ανθρώπους έφτασε, με ποιο κόστος ανά άνθρωπο, έτοιμο για δημοσιοποίηση.' },
    },
    size: {
      ngo: 'Πόσους ανθρώπους στηρίζετε τον χρόνο;',
      med: 'Πόσοι γιατροί δουλεύουν μαζί σας;',
      sponsor: ['Πόσους οργανισμούς θέλετε να στηρίξετε;', 'Πόσους ανθρώπους φτάνουν τον χρόνο;', 'Για πόσο καιρό;', 'Σε ποιον τομέα;'],
      years: ['1 χρόνο', '2 χρόνια'],
      people: 'άνθρωποι τον χρόνο',
    },
    groups: { logos: 'DialogosAI · μιλά', praxis: 'PraxisAI · θυμάται', insights: 'MetronAI · μετρά', extra: 'Επιλογές για φορείς' },
    included: 'Περιλαμβάνεται',
    always: 'Πάντα μέσα',
    soon: 'Σύντομα',
    atCost: 'φιλοξενία στο κόστος',
    recommended: 'Προτείνεται',
    perMonth: '/μήνα',
    setup: 'εφάπαξ',
    billing: ['Μηνιαία', 'Ετήσια'],
    annualNote: 'Με ετήσια συνδρομή η ένταξη είναι δωρεάν.',
    pains: {
      title: 'Πού χάνεται ο χρόνος σας σήμερα;',
      hint: 'Πατήστε όσα ισχύουν. Θα φανούν αριστερά στη ροή.',
      ngo: ['Τηλέφωνα από οικογένειες', 'Σημειώσεις σε χαρτιά και Excel', 'Ξεχασμένες λήξεις', 'Αναφορές για χορηγούς', 'Ερωτήσεις για δικαιώματα', 'Μηνύματα εκτός ωραρίου'],
      med: ['Αναπάντητες κλήσεις', 'Ακυρώσεις χωρίς αντικατάσταση', 'Ερωτήσεις για τιμές και ΕΟΠΥΥ', 'Ξεχασμένοι επανέλεγχοι', 'Ιστορικό στην αίθουσα αναμονής', 'Μηνύματα σε 4 εφαρμογές'],
      sponsor: ['Δεν ξέρουμε πόσους φτάσαμε', 'Αναφορές που αργούν', 'Φόβος για συμμόρφωση', 'Χορηγίες χωρίς διάρκεια', 'Δύσκολη δημοσιοποίηση', 'Κανείς δεν βλέπει το αποτέλεσμα'],
      q2: { ngo: 'Πόσα τηλέφωνα και μηνύματα δέχεστε τη μέρα;', med: 'Πόσες κλήσεις χάνετε τη μέρα;', sponsor: 'Τι θέλετε να δείχνει η αναφορά;' },
      a2: { ngo: ['Λιγότερα από 10', '10 – 30', 'Πάνω από 30'], med: ['1 – 2', '3 – 5', 'Πάνω από 5'], sponsor: ['Ανθρώπους που ενημερώθηκαν', 'Ανάγκες χωρίς απάντηση', 'Γεωγραφική κάλυψη', 'Ικανοποίηση'] },
      q3: 'Πότε θα θέλατε να ξεκινήσετε;',
      a3: ['Τώρα', 'Σε 1 – 3 μήνες', 'Ψάχνουμε χρηματοδότηση'],
    },
    graphic: { today: 'Σήμερα', withFlow: 'Με fλow', empty: 'Επιλέξτε τι θέλετε να ρέει', aria: 'Η ροή σας: αριστερά όσα σας δυσκολεύουν σήμερα, στη μέση το fλow, δεξιά όσα επιλέξατε.' },
    offer: {
      title: 'Η προσφορά σας',
      plan: 'Πακέτο',
      monthly: 'Μηνιαία',
      setup: 'Ένταξη στη ροή',
      firstYear: 'Πρώτος χρόνος',
      from: 'από',
      worth: 'Αξία αν τα αγοράζατε χωριστά',
      pilot: 'Ή ξεκινήστε με δοκιμή 60 ημερών με 490 €, που αφαιρούνται από την ένταξη.',
      guarantee: 'Εγγύηση: αν στις 60 μέρες δεν απαντά σωστά στο 90% των ερωτήσεων που συμφωνήσαμε, η συνδρομή είναι δωρεάν ώσπου να το πετύχει.',
      guaranteeMed: 'Live σε 48 ώρες, αλλιώς δωρεάν. Αν δεν φτάσει το 90% ακρίβεια στο τεστ αποδοχής, δεν πληρώνετε.',
      funding: 'Συχνά δεν το πληρώνει ο οργανισμός. Σας βοηθάμε να βρείτε χορηγό, CSR ή ευρωπαϊκό πρόγραμμα.',
      custom: 'Για αυτό το μέγεθος φτιάχνουμε προσφορά μαζί σας. Η τιμή είναι η αφετηρία.',
      total: 'Συνολικό κόστος',
      orgs: 'Οργανισμοί',
      perPerson: 'ανά άνθρωπο που φτάνει, τον χρόνο',
      sponsorWhat: 'Τι παίρνετε',
      sponsorList: ['Αναφορά αντίκτυπου κάθε τρίμηνο', 'Φάκελος έτοιμος για δημοσιοποίηση (ΣΦΕΕ / EFPIA)', 'Ο οργανισμός ελέγχει το περιεχόμενο· ο χορηγός δεν επηρεάζει απαντήσεις', 'Καμία ιατρική συμβουλή, καμία προώθηση προϊόντος', 'Σύμφωνο με EU AI Act και GDPR, φιλοξενία στην ΕΕ', '«Με την υποστήριξη του …» σε κάθε συνομιλία'],
      oneNumber: 'Ο αριθμός που θα βλέπετε κάθε μήνα',
      oneNumberText: 'Ερωτήσεις που απαντήθηκαν από εγκεκριμένες πηγές',
      proof: 'Το ΣΚΠ-i της ΠΟΑμΣΚΠ λειτουργεί ήδη με την υποστήριξη φαρμακευτικών εταιρειών.',
      note: 'Τιμές χωρίς ΦΠΑ. Φιλοξενία και χρήση AI στο κόστος τους. Η προσφορά ισχύει 30 μέρες.',
    },
    contact: {
      title: 'Στείλτε μας τη ροή σας',
      lead: 'Σας απαντάμε μέσα σε μία εργάσιμη με την προσφορά σε PDF και μια πρόταση για 30 λεπτά.',
      name: 'Όνομα', org: 'Οργανισμός', email: 'Email', phone: 'Τηλέφωνο (προαιρετικό)',
      consent: 'Συμφωνώ να επικοινωνήσει μαζί μου η SimasiaAI για αυτή την προσφορά.',
      send: 'Στείλτε την προσφορά',
      print: 'Κατεβάστε την ως PDF',
      printSponsor: 'Κατεβάστε το one-pager',
      sending: 'Αποστολή…',
      sent: 'Τη λάβαμε. Θα σας γράψουμε μέσα σε μία εργάσιμη.',
      fallback: 'Η αποστολή δεν έγινε από εδώ. Ανοίξτε το email σας με την προσφορά έτοιμη:',
      fallbackLink: 'Άνοιγμα email',
      required: 'Συμπληρώστε όνομα, email και τη συγκατάθεση.',
    },
    summaryBar: 'Δείτε την προσφορά',
    back: 'Πίσω',
    eyebrow: 'Go with the fλow',
    stack: {
      title: 'Μαζί με τη συνδρομή, χωρίς επιπλέον χρέωση',
      items: [
        ['Προσωπικός project manager, ένας άνθρωπος από την πρώτη μέρα', 900],
        ['Τακτοποιούμε τα αρχεία σας και φτιάχνουμε τη βάση γνώσης, χωρίς δική σας δουλειά', 350],
        ['Τεστ αποδοχής σε 50 ερωτήσεις και απαντήσεις, πριν βγει στους ανθρώπους σας', 400],
        ['Εκπαίδευση της ομάδας: οδηγός και video στη γλώσσα της', 150],
        ['QR και έντυπα για να το βρίσκουν οι άνθρωποί σας', 100],
        ['Πάντα τα νεότερα και ισχυρότερα μοντέλα AI', 400],
        ['Μηνιαίες συναντήσεις με την ομάδα μας', 600],
        ['Επείγουσες διορθώσεις μέσα σε 24 ώρες', 300],
        ['Υποστήριξη μέσω chat, 24/7', 250],
        ['Αναφορά για όσα ζήτησαν οι άνθρωποί σας και δεν βρήκαν', 500],
      ],
      worth: 'Αξία', you: 'Για εσάς', free: '0 €',
    },
    assure: {
      title: 'Δεν ρισκάρετε τίποτα',
      ngo: [['Δοκιμή 60 ημερών', 'Με 490 € που αφαιρούνται από την ένταξη.'], ['Εγγύηση ακρίβειας', '90% σωστές απαντήσεις στις ερωτήσεις που συμφωνήσαμε, αλλιώς δωρεάν ώσπου να το πετύχει.'], ['Ένας άνθρωπος δίπλα σας', 'Ο project manager σας, από το πρώτο τηλεφώνημα μέχρι μετά το live.']],
      med: [['Live σε 48 ώρες', 'Ή δωρεάν. Αυτή είναι η εγγύησή μας.'], ['Τεστ αποδοχής', 'Αν δεν φτάσει το 90% ακρίβεια, δεν πληρώνετε.'], ['Ένας άνθρωπος δίπλα σας', 'Ο project manager σας, από το πρώτο τηλεφώνημα μέχρι μετά το live.']],
      sponsor: [['Μετριέται κάθε μήνα', 'Βλέπετε πόσους έφτασε, πριν το δει οποιοσδήποτε άλλος.'], ['Συμμόρφωση πρώτα', 'Νομικός έλεγχος σε κάθε έργο, χωρίς προώθηση προϊόντος.'], ['Ένας άνθρωπος δίπλα σας', 'Project manager για χορηγό και οργανισμό.']],
    },
    unique: {
      title: 'Κάθε οργανισμός είναι μοναδικός',
      text: 'Το fλow στήνεται πάνω στα δικά σας έγγραφα, στο όνομα, στον τόνο και στα κανάλια σας. Ξεκινάτε από το κομμάτι που σας πονά και προσθέτετε το επόμενο όταν είστε έτοιμοι. Η τιμή εδώ είναι η αφετηρία· στη συζήτηση την προσαρμόζουμε σε εσάς.',
    },
    impact: {
      ngo: 'Κάθε απάντηση είναι ένας άνθρωπος που δεν περίμενε μέχρι αύριο.',
      med: 'Κάθε κλήση που απαντιέται είναι ένας ασθενής που δεν πήγε αλλού.',
      sponsor: 'Κάθε ευρώ φτάνει σε ανθρώπους, και φαίνεται.',
    },
    faq: {
      title: 'Ό,τι σας κρατά πίσω, απαντημένο',
      ngo: [
        ['Είναι ακριβό για εμάς.', 'Συχνά δεν το πληρώνει ο οργανισμός: σας βοηθάμε να βρείτε χορηγό, CSR ή ευρωπαϊκό πρόγραμμα. Κι αν απαντήσει μόνο σε 10 τηλέφωνα τη μέρα, σας δίνει πίσω πάνω από 10 ώρες τον μήνα.'],
        ['Η ομάδα δεν έχει χρόνο για κάτι καινούργιο.', 'Δεν χρειάζεται. Στήνουμε εμείς, με τα δικά σας έγγραφα. Η ομάδα παίρνει μία εκπαίδευση, έναν οδηγό στη γλώσσα της και έναν άνθρωπο να ρωτά.'],
        ['Δεν είμαστε τεχνικοί.', 'Δεν χρειάζεται κώδικας ούτε τμήμα IT. Αν μπορείτε να στείλετε ένα email, μπορείτε να δουλέψετε με το fλow.'],
        ['Κι αν απαντήσει λάθος;', 'Απαντά μόνο από ό,τι εγκρίνατε, με παραπομπή στην πηγή, και όταν δεν ξέρει το λέει. Κανένα AI δεν είναι αλάθητο: γι\' αυτό τεστ πριν το live, έλεγχος κάθε μήνα, και τα επείγοντα πάντα σε άνθρωπο.'],
        ['Τι γίνεται με τα δεδομένα μας;', 'Φιλοξενούνται στην ΕΕ και ανήκουν σε εσάς. Υπογράφουμε σύμβαση επεξεργασίας δεδομένων, όπως ορίζει ο GDPR.'],
        ['Και ο AI Act;', 'Είναι η πρώτη μας προτεραιότητα. Το σύστημα δηλώνει ότι είναι AI, ο άνθρωπος μένει στον έλεγχο, και κάθε έργο το αξιολογεί ξεχωριστά συνεργαζόμενη νομική εταιρεία.'],
        ['Κι αν τελικά δεν μας κάνει;', 'Ξεκινάτε με δοκιμή 60 ημερών και εγγύηση ακρίβειας. Δεν δεσμεύεστε σε τίποτα πριν δείτε τη ροή να δουλεύει.'],
      ],
      med: [
        ['Είναι ακριβό για ένα ιατρείο.', 'Δύο ραντεβού που δεν χάνονται τον μήνα συνήθως καλύπτουν τη συνδρομή. Με ετήσια, η ένταξη είναι δωρεάν.'],
        ['Η γραμματεία δεν έχει χρόνο να μάθει κάτι καινούργιο.', 'Δεν χρειάζεται. Στήνουμε εμείς, από τον τιμοκατάλογο και τις πληροφορίες σας. Η γραμματεία κερδίζει χρόνο από την πρώτη εβδομάδα.'],
        ['Δεν είμαι τεχνικός.', 'Δεν χρειάζεται. Live σε 48 ώρες, χωρίς κώδικα, με έναν άνθρωπο να ρωτάτε.'],
        ['Κι αν απαντήσει λάθος σε ασθενή;', 'Δεν δίνει ποτέ ιατρική συμβουλή ή διάγνωση. Απαντά μόνο από ό,τι εγκρίνατε, και ό,τι είναι επείγον πάει σε άνθρωπο. Κανένα AI δεν είναι αλάθητο: γι\' αυτό τεστ πριν το live και έλεγχος κάθε μήνα.'],
        ['Τι γίνεται με τα δεδομένα των ασθενών;', 'Φιλοξενούνται στην ΕΕ και ανήκουν σε εσάς. Υπογράφουμε σύμβαση επεξεργασίας δεδομένων, όπως ορίζει ο GDPR.'],
        ['Και ο AI Act;', 'Είναι η πρώτη μας προτεραιότητα. Κάθε έργο το αξιολογεί ξεχωριστά συνεργαζόμενη νομική εταιρεία.'],
      ],
      sponsor: [
        ['Πώς ξέρουμε ότι η στήριξη έφτασε;', 'Με αναφορά κάθε τρίμηνο: πόσοι άνθρωποι ενημερώθηκαν, τι ρώτησαν, τι έλειπε. Με κόστος ανά άνθρωπο.'],
        ['Είναι σύμφωνο με τους κώδικες του κλάδου;', 'Ο οργανισμός ελέγχει το περιεχόμενο, ο χορηγός δεν επηρεάζει απαντήσεις, καμία προώθηση προϊόντος. Φάκελος έτοιμος για δημοσιοποίηση (ΣΦΕΕ / EFPIA).'],
        ['Και ο AI Act;', 'Πρώτη μας προτεραιότητα. Κάθε έργο το αξιολογεί ξεχωριστά συνεργαζόμενη νομική εταιρεία.'],
        ['Κι αν ο οργανισμός δεν το χρησιμοποιήσει;', 'Το βλέπετε στους αριθμούς κάθε μήνα, και ο project manager παρεμβαίνει πριν γίνει πρόβλημα.'],
      ],
    },
    bookLink: 'Ή κλείστε 30 λεπτά μαζί μας',
  },
  en: {
    title: 'Build your fλow',
    lead: 'Choose who you are and what you want to run more quietly. The flow and the price change in front of you. At the end you get your offer.',
    steps: ['Who you are', 'How many you support', 'What should flow', 'Your day today', 'Your offer'],
    who: {
      ngo: { name: 'Organisation or NGO', line: 'Patient groups, disability services, federations', pitch: 'For you, fλow starts with DialogosAI and MetronAI: answers for your people, and data that shows your team and sponsors what they need.' },
      med: { name: 'Practice or clinic', line: 'Doctors, polyclinics, diagnostics', pitch: 'For you, fλow is first PraxisAI: every call and message becomes a booking or a patient card, even while you examine.' },
      sponsor: { name: 'Sponsor', line: 'Pharma, foundations, companies with CSR', pitch: 'For you, fλow is support you can measure: how many people it reached, at what cost per person, ready for disclosure.' },
    },
    size: {
      ngo: 'How many people do you support a year?',
      med: 'How many doctors work with you?',
      sponsor: ['How many organisations do you want to support?', 'How many people do they reach a year?', 'For how long?', 'In which area?'],
      years: ['1 year', '2 years'],
      people: 'people a year',
    },
    groups: { logos: 'DialogosAI · talks', praxis: 'PraxisAI · remembers', insights: 'MetronAI · measures', extra: 'Options for public bodies' },
    included: 'Included', always: 'Always in', soon: 'Soon', atCost: 'hosting at cost', recommended: 'Recommended',
    perMonth: '/month', setup: 'one-off', billing: ['Monthly', 'Annual'], annualNote: 'With annual billing, onboarding is free.',
    pains: {
      title: 'Where does your time go today?',
      hint: 'Tap all that apply. They appear on the left of the flow.',
      ngo: ['Calls from families', 'Notes on paper and Excel', 'Missed expiry dates', 'Reports for sponsors', 'Questions about rights', 'Messages after hours'],
      med: ['Missed calls', 'Cancellations left empty', 'Questions on prices and insurance', 'Forgotten check-ups', 'History filled in the waiting room', 'Messages in 4 apps'],
      sponsor: ['We don\'t know how many we reached', 'Reports arrive late', 'Compliance worries', 'Sponsorships without continuity', 'Hard to disclose', 'Nobody sees the result'],
      q2: { ngo: 'How many calls and messages a day?', med: 'How many calls do you miss a day?', sponsor: 'What should the report show?' },
      a2: { ngo: ['Fewer than 10', '10 – 30', 'More than 30'], med: ['1 – 2', '3 – 5', 'More than 5'], sponsor: ['People informed', 'Unmet needs', 'Geographic reach', 'Satisfaction'] },
      q3: 'When would you like to start?',
      a3: ['Now', 'In 1 – 3 months', 'Looking for funding'],
    },
    graphic: { today: 'Today', withFlow: 'With fλow', empty: 'Choose what should flow', aria: 'Your flow: on the left what is hard today, fλow in the middle, on the right what you chose.' },
    offer: {
      title: 'Your offer', plan: 'Plan', monthly: 'Monthly', setup: 'Onboarding into the flow', firstYear: 'First year', from: 'from',
      worth: 'Value if bought separately',
      pilot: 'Or start with a 60-day pilot for €490, credited against onboarding.',
      guarantee: 'Guarantee: if at 60 days it doesn\'t answer 90% of our agreed questions correctly, the subscription is free until it does.',
      guaranteeMed: 'Live in 48 hours, or free. If it doesn\'t reach 90% accuracy in the acceptance test, you don\'t pay.',
      funding: 'Often the organisation doesn\'t pay. We help you find a sponsor, CSR or EU programme.',
      custom: 'For this size we build the offer with you. The price is the starting point.',
      total: 'Total cost', orgs: 'Organisations', perPerson: 'per person reached, per year',
      sponsorWhat: 'What you get',
      sponsorList: ['Quarterly impact report', 'Disclosure-ready file (SFEE / EFPIA)', 'The organisation controls content; the sponsor never shapes answers', 'No medical advice, no product promotion', 'EU AI Act and GDPR compliant, hosted in the EU', '"Supported by …" in every conversation'],
      oneNumber: 'The number you will see every month', oneNumberText: 'Questions answered from approved sources',
      proof: 'ΣΚΠ-i by POAmSKP already runs with the support of pharmaceutical companies.',
      note: 'Prices exclude VAT. Hosting and AI usage at cost. Offer valid for 30 days.',
    },
    contact: {
      title: 'Send us your flow', lead: 'We reply within one working day with the offer as a PDF and a 30-minute slot.',
      name: 'Name', org: 'Organisation', email: 'Email', phone: 'Phone (optional)',
      consent: 'I agree that SimasiaAI may contact me about this offer.',
      send: 'Send the offer', print: 'Download as PDF', printSponsor: 'Download the one-pager', sending: 'Sending…',
      sent: 'Received. We will write to you within one working day.',
      fallback: 'It could not be sent from here. Open your email with the offer ready:', fallbackLink: 'Open email',
      required: 'Please fill in name, email and consent.',
    },
    summaryBar: 'See the offer',
    back: 'Back',
    eyebrow: 'Go with the fλow',
    stack: {
      title: 'Included with your subscription, at no extra cost',
      items: [
        ['A personal project manager, one person from day one', 900],
        ['We organise your files and build your knowledge base, with no work on your side', 350],
        ['Acceptance test on 50 questions and answers, before it reaches your people', 400],
        ['Team training: a guide and video in their language', 150],
        ['QR codes and print material so your people find it', 100],
        ['Always the newest, strongest AI models', 400],
        ['Monthly meetings with our team', 600],
        ['Urgent fixes within 24 hours', 300],
        ['Chat support, 24/7', 250],
        ['A report on what your people asked for and did not find', 500],
      ],
      worth: 'Worth', you: 'For you', free: '€0',
    },
    assure: {
      title: 'You risk nothing',
      ngo: [['60-day pilot', 'For €490, credited against onboarding.'], ['Accuracy guarantee', '90% correct answers on the questions we agree, or it is free until it gets there.'], ['One person beside you', 'Your project manager, from the first call to well after launch.']],
      med: [['Live in 48 hours', 'Or it is free. That is our guarantee.'], ['Acceptance test', 'If it does not reach 90% accuracy, you don\'t pay.'], ['One person beside you', 'Your project manager, from the first call to well after launch.']],
      sponsor: [['Measured every month', 'You see how many people it reached before anyone else does.'], ['Compliance first', 'Legal review on every project, no product promotion.'], ['One person beside you', 'A project manager for sponsor and organisation.']],
    },
    unique: {
      title: 'Every organisation is unique',
      text: 'fλow is set up on your own documents, name, tone and channels. You start with the part that hurts most and add the next one when you are ready. The price here is the starting point; in our conversation we fit it to you.',
    },
    impact: {
      ngo: 'Every answer is a person who did not have to wait until tomorrow.',
      med: 'Every call answered is a patient who did not go elsewhere.',
      sponsor: 'Every euro reaches people, and it shows.',
    },
    faq: {
      title: 'What holds you back, answered',
      ngo: [
        ['It is too expensive for us.', 'Often the organisation doesn\'t pay: we help you find a sponsor, CSR or an EU programme. And if it answers only 10 calls a day, it gives you back more than 10 hours a month.'],
        ['Our team has no time for something new.', 'It doesn\'t need any. We set it up, from your documents. The team gets one training, a guide in their language and one person to ask.'],
        ['We are not technical.', 'No code, no IT department. If you can send an email, you can work with fλow.'],
        ['What if it answers wrongly?', 'It answers only from what you approved, with a source, and says so when it doesn\'t know. No AI is infallible: so a test before launch, a check every month, and urgent cases always go to a person.'],
        ['What about our data?', 'It is hosted in the EU and belongs to you. We sign a data processing agreement, as the GDPR requires.'],
        ['And the AI Act?', 'It is our first priority. The system says it is AI, people stay in control, and a partner law firm reviews every project separately.'],
        ['What if it is not right for us?', 'You start with a 60-day pilot and an accuracy guarantee. You commit to nothing before you see the flow working.'],
      ],
      med: [
        ['It is expensive for a practice.', 'Two appointments a month that are not lost usually cover the subscription. With annual billing, onboarding is free.'],
        ['The front desk has no time to learn something new.', 'It doesn\'t need any. We set it up from your price list and information. The front desk gains time from the first week.'],
        ['I am not technical.', 'No need. Live in 48 hours, no code, with one person to ask.'],
        ['What if it tells a patient something wrong?', 'It never gives medical advice or diagnosis. It answers only from what you approved, and anything urgent goes to a person. No AI is infallible: so a test before launch and a check every month.'],
        ['What about patient data?', 'It is hosted in the EU and belongs to you. We sign a data processing agreement, as the GDPR requires.'],
        ['And the AI Act?', 'It is our first priority. A partner law firm reviews every project separately.'],
      ],
      sponsor: [
        ['How do we know the support arrived?', 'A report every quarter: how many people were informed, what they asked, what was missing. With cost per person.'],
        ['Does it follow industry codes?', 'The organisation controls content, the sponsor never shapes answers, no product promotion. A disclosure-ready file (SFEE / EFPIA).'],
        ['And the AI Act?', 'Our first priority. A partner law firm reviews every project separately.'],
        ['What if the organisation does not use it?', 'You see it in the numbers every month, and the project manager steps in before it becomes a problem.'],
      ],
    },
    bookLink: 'Or book 30 minutes with us',
  },
};
