// fλow — copy for the home page (Greek + English).
// fλow is the product; Pyxida is its assistant (chatbot).
// Prices exclude VAT. Hosting and AI usage are billed at cost.

export const flowContent = {
  el: {
    pill: 'Για οργανισμούς φροντίδας και ιατρεία',
    assistant: 'Pyxida',
    by: 'από τη SimasiaAI',
    title1: 'Η φροντίδα',
    title2: 'να ρέει.',
    sub: 'Το Pyxida, ο ψηφιακός βοηθός που απαντά στους ανθρώπους σας μέρα και νύχτα, και ένα CRM που γεμίζει μόνο του. Στα ελληνικά, με έγκριση από άνθρωπο.',
    ctaMain: 'Ζητήστε δωρεάν διάγνωση ροής',
    ctaDay: 'Δείτε μια μέρα με fλow',
    streamAria: 'Τηλέφωνα, Viber, χαρτιά, email και ξεχασμένες λήξεις μπαίνουν στο fλow και βγαίνουν ως ήρεμες, παράλληλες ροές',
    streamIn: ['Τηλέφωνα', 'Viber', 'Χαρτιά', 'Excel', 'Email', 'Ξεχασμένες λήξεις'],
    streamOut: ['Pyxida 24/7', 'Φάκελος', 'Καταγραφή', 'Υπενθυμίσεις', 'Insights', 'Ήρεμες οικογένειες'],
    edAria: 'Έκδοση',
    edNgo: 'Οργανισμοί & ΜΚΟ',
    edMed: 'Ιατρεία & Κλινικές',
    dayEyebrow: 'Μια μέρα με fλow',
    dayTitle: 'Το ίδιο πρόγραμμα. Άλλη αίσθηση.',
    dayLead: 'Πάνω: πώς είναι σήμερα. Κάτω: πώς είναι με το fλow.',
    howEyebrow: 'Πώς δουλεύει',
    howTitle: 'Τρία κομμάτια, μία ροή.',
    howLead: 'Το Pyxida και το CRM δουλεύουν και μόνα τους. Μαζί, το Pyxida μιλά μόνο με ό,τι έχει εγκρίνει άνθρωπος.',
    parts: {
      a: { k: 'Μπροστά', h: 'Pyxida, ο βοηθός', p: 'Στο site, στο Viber και στο WhatsApp. Απαντά μόνο από τις πηγές σας, με παραπομπή.' },
      m: { k: 'Στη μέση', h: 'Έγκριση από άνθρωπο', p: 'Το AI γράφει το προσχέδιο. Ένας άνθρωπος της ομάδας σας εγκρίνει πριν φύγει οτιδήποτε.', list: ['Κάθε αίτημα με υπεύθυνο', 'Πλήρες ιστορικό για έλεγχο', 'Λέει «δεν ξέρω» όταν δεν ξέρει'] },
      c: { k: 'Πίσω', h: 'fλow CRM', p: 'Η εφαρμογή της ομάδας σε κινητό και υπολογιστή. Γεμίζει με κουμπιά ή με φωνή.' },
    },
    insEyebrow: 'fλow Insights',
    insTitle: 'Κάθε συνομιλία γίνεται γνώση.',
    insLead: {
      ngo: 'Τι ρωτούν οι άνθρωποί σας, τι μένει αναπάντητο, πού χρειάζεται βοήθεια. Κάθε μήνα, έτοιμο για τους χορηγούς σας.',
      med: 'Τι ρωτούν οι ασθενείς σας, τι ζήτηση χάνεται εκτός ωραρίου, πού μένουν κενά στο πρόγραμμα.',
    },
    insAria: 'Παράδειγμα πίνακα Insights με δοκιμαστικά δεδομένα',
    sample: 'Παράδειγμα',
    tConv: 'Συνομιλίες τον μήνα', tConvS: '87% απαντήθηκαν από τις πηγές σας',
    tAfter: 'Εκτός ωραρίου', tAfterS: 'των ερωτήσεων έρχεται όταν το γραφείο είναι κλειστό',
    tMood: 'Διάθεση συνομιλιών', tMoodS: 'Όλο και πιο θετική μέσα στον μήνα',
    tThemes: 'Τι ρωτούν οι άνθρωποί σας',
    tNeeds: 'Ανάγκες χωρίς απάντηση', tNeedsS: 'Γίνονται η επόμενη πρότασή σας.', questions: 'ερωτήσεις',
    proofEyebrow: 'Ήδη σε λειτουργία',
    proofTitle: 'Γεννήθηκε μέσα σε πραγματικούς οργανισμούς.',
    proof: [
      { n: 'Myrto', p: 'Ψηφιακός πλοηγός για ασθενείς με καρκίνο και τις οικογένειές τους.', s: 'Κάπα3 · με την υποστήριξη του Ιδρύματος ΤΙΜΑ' },
      { n: 'ΣΚΠ-i', p: 'Καθημερινή υποστήριξη και αξιόπιστη ενημέρωση για την κοινότητα της Σκλήρυνσης κατά Πλάκας.', s: 'ΠΟΑΜΣΚΠ' },
    ],
    priceEyebrow: 'Τιμές',
    priceTitle: 'Ξεκάθαρες τιμές. Χωρίς εκπλήξεις.',
    perMonth: '/μήνα',
    setup: 'Ένταξη στη ροή',
    worth: 'Αξία αν τα αγοράζατε χωριστά',
    recFlag: 'Οι περισσότεροι ξεκινούν εδώ',
    allFeatures: 'Όλα τα χαρακτηριστικά',
    priceNote: 'Τιμές χωρίς ΦΠΑ. Φιλοξενία και χρήση AI στο κόστος τους.',
    pilotTitle: 'Δοκιμάστε το 60 ημέρες με 490 €',
    pilotText: 'Με τα δικά σας δεδομένα. Αν συνεχίσετε, τα 490 € αφαιρούνται ολόκληρα από την ένταξη.',
    guarB: 'Εγγύηση ακρίβειας:',
    guar: 'στις 60 ημέρες το Pyxida απαντά σωστά τουλάχιστον στο 90% των δοκιμαστικών ερωτήσεων που συμφωνούμε. Αλλιώς, η συνδρομή είναι δωρεάν μέχρι να το πετύχει.',
    pilotCta: 'Ξεκινήστε',
    onbEyebrow: 'Ένταξη στη ροή',
    onbTitle: 'Δεν πληρώνετε εγκατάσταση. Πληρώνετε τη μετάβαση.',
    steps: [
      ['Καταγραφή αναγκών', 'Ερωτηματολόγιο 5 λεπτών για την ομάδα και ένα εργαστήριο.'],
      ['Ρύθμιση', 'Η γνώση σας, το όνομα, το ύφος, τα κανάλια. Χωρίς κώδικα για εσάς.'],
      ['Εκπαίδευση', 'Συναντήσεις, οδηγός στα ελληνικά, ένας πρεσβευτής σε κάθε ομάδα.'],
      ['Παρακολούθηση 90 ημερών', 'Μηνιαίο τεστ ακρίβειας και διορθώσεις, μέχρι η ροή να σταθεί.'],
    ],
    trustEyebrow: 'Εμπιστοσύνη',
    trustTitle: 'Το AI βοηθά. Οι άνθρωποι αποφασίζουν.',
    trust: [
      ['Μόνο εγκεκριμένες πηγές', 'Με παραπομπή. Όταν δεν ξέρει, το λέει.'],
      ['Έγκριση από άνθρωπο', 'Τίποτα δεν φεύγει χωρίς έγκριση.'],
      ['Καμία ιατρική συμβουλή', 'Ούτε διάγνωση, ούτε αλλαγή αγωγής.'],
      ['EU AI Act · GDPR', 'Δηλώνει ότι είναι AI. Φιλοξενία στην ΕΕ.'],
    ],
    finalEyebrow: 'Δωρεάν διάγνωση ροής',
    finalTitle: 'Μάθετε πού χάνεται ο χρόνος της ομάδας σας.',
    finalLead: 'Στέλνουμε ένα ερωτηματολόγιο 5 λεπτών στην ομάδα σας και σας επιστρέφουμε χάρτη: πού χάνονται ώρες, τι ρωτούν οι άνθρωποί σας, τι λήγει.',
    finalCta: 'Κλείστε 30 λεπτά',
    copy: 'Αντιγραφή email', copied: 'Αντιγράφηκε.',
  },
  en: {
    pill: 'For care organisations and clinics',
    assistant: 'Pyxida',
    by: 'by SimasiaAI',
    title1: 'Let care',
    title2: 'flow.',
    sub: 'Pyxida, the digital assistant that answers your people day and night, and a CRM that fills itself. In your language, with a human approving.',
    ctaMain: 'Get a free flow diagnosis',
    ctaDay: 'See a day with fλow',
    streamAria: 'Phone calls, Viber, paper, email and missed deadlines enter fλow and leave as calm, parallel streams',
    streamIn: ['Phone calls', 'Viber', 'Paper', 'Excel', 'Email', 'Missed deadlines'],
    streamOut: ['Pyxida 24/7', 'Case file', 'Daily log', 'Reminders', 'Insights', 'Calm families'],
    edAria: 'Edition',
    edNgo: 'Organisations & NGOs',
    edMed: 'Practices & Clinics',
    dayEyebrow: 'A day with fλow',
    dayTitle: 'Same schedule. Different feeling.',
    dayLead: 'Top: how it is today. Bottom: how it is with fλow.',
    howEyebrow: 'How it works',
    howTitle: 'Three parts, one flow.',
    howLead: 'Pyxida and the CRM work on their own. Together, Pyxida only says what a human has approved.',
    parts: {
      a: { k: 'Front', h: 'Pyxida, the assistant', p: 'On your site, Viber and WhatsApp. Answers only from your sources, with a citation.' },
      m: { k: 'Middle', h: 'Human approval', p: 'AI writes the draft. Someone on your team approves before anything goes out.', list: ['Every request has an owner', 'Full history for audits', 'Says "I don\'t know" when it doesn\'t'] },
      c: { k: 'Back', h: 'fλow CRM', p: 'Your team\'s app on phone and desktop. Filled with taps or by voice.' },
    },
    insEyebrow: 'fλow Insights',
    insTitle: 'Every conversation becomes knowledge.',
    insLead: {
      ngo: 'What your people ask, what stays unanswered, where help is needed. Every month, ready for your funders.',
      med: 'What your patients ask, which demand is lost after hours, where your schedule has gaps.',
    },
    insAria: 'Sample Insights dashboard with test data',
    sample: 'Sample',
    tConv: 'Conversations per month', tConvS: '87% answered from your sources',
    tAfter: 'After hours', tAfterS: 'of questions arrive while the office is closed',
    tMood: 'Conversation sentiment', tMoodS: 'Steadily more positive through the month',
    tThemes: 'What your people ask',
    tNeeds: 'Unmet needs', tNeedsS: 'They become your next proposal.', questions: 'questions',
    proofEyebrow: 'Already live',
    proofTitle: 'Born inside real organisations.',
    proof: [
      { n: 'Myrto', p: 'A digital navigator for people with cancer and their families.', s: 'Kapa3 · supported by the TIMA Foundation' },
      { n: 'ΣΚΠ-i', p: 'Daily support and reliable information for the Multiple Sclerosis community.', s: 'POAMSKP' },
    ],
    priceEyebrow: 'Pricing',
    priceTitle: 'Clear prices. No surprises.',
    perMonth: '/month',
    setup: 'Onboarding into the flow',
    worth: 'Value if bought separately',
    recFlag: 'Most start here',
    allFeatures: 'All features',
    priceNote: 'Prices exclude VAT. Hosting and AI usage at cost.',
    pilotTitle: 'Try it for 60 days for €490',
    pilotText: 'With your own data. If you continue, the full €490 is credited against onboarding.',
    guarB: 'Accuracy guarantee:',
    guar: 'at 60 days Pyxida answers at least 90% of our agreed test questions correctly. Otherwise, the subscription is free until it does.',
    pilotCta: 'Get started',
    onbEyebrow: 'Onboarding into the flow',
    onbTitle: 'You don\'t pay for installation. You pay for the transition.',
    steps: [
      ['Needs mapping', 'A 5-minute team survey and one workshop.'],
      ['Configuration', 'Your knowledge, name, tone and channels. No code on your side.'],
      ['Training', 'Sessions, a guide in your language, one champion per team.'],
      ['90-day follow-up', 'Monthly accuracy test and fixes until the flow holds.'],
    ],
    trustEyebrow: 'Trust',
    trustTitle: 'AI assists. People decide.',
    trust: [
      ['Approved sources only', 'With citations. When it doesn\'t know, it says so.'],
      ['Human approval', 'Nothing goes out unapproved.'],
      ['No medical advice', 'No diagnosis, no treatment changes.'],
      ['EU AI Act · GDPR', 'Discloses it is AI. Hosted in the EU.'],
    ],
    finalEyebrow: 'Free flow diagnosis',
    finalTitle: 'Find out where your team\'s time goes.',
    finalLead: 'We send your team a 5-minute survey and return a map: where hours are lost, what your people ask, what is about to expire.',
    finalCta: 'Book 30 minutes',
    copy: 'Copy email', copied: 'Copied.',
  },
};

// Edition data (per language). Each day row: [time, before, afterBold, afterRest]
export const editions = {
  el: {
    ngo: {
      day: [
        ['08:00', 'Η βάρδια ξεκινά ψάχνοντας σημειώσεις σε τετράδια.', 'Η παράδοση βάρδιας είναι έτοιμη', ' σε μία οθόνη.'],
        ['10:30', 'Τρία τηλέφωνα: «πώς είναι;». Η δουλειά σταματά.', 'Το Pyxida απαντά', ' από την εγκεκριμένη σύνοψη.'],
        ['16:00', 'Μια πιστοποίηση αναπηρίας έληξε χωρίς να το δει κανείς.', 'Υπενθύμιση 60, 30 και 7 ημέρες πριν.', ''],
        ['18:00', 'Η αναφορά για τον χορηγό: δύο βράδια σε Excel.', 'Η μηνιαία αναφορά', ' βγαίνει μόνη της.'],
      ],
      A: ['Δικαιώματα και παροχές (ΚΕΠΑ, ΟΠΕΚΑ)', 'Εγγραφές, δωρεές, εθελοντισμός', 'Πρωτόκολλο κρίσης'],
      C: ['Φάκελοι και καταγραφή σε ένα λεπτό', 'Λήξεις και υπενθυμίσεις', 'Ενημερώσεις οικογενειών με έγκριση'],
      th: [['ΚΕΠΑ και πιστοποίηση', 31], ['Επιδόματα ΟΠΕΚΑ', 22], ['Ραντεβού και νοσοκομεία', 17], ['Ψυχολογική στήριξη', 12], ['Δωρεές και εθελοντισμός', 8]],
      nd: [['Μεταφορά προς θεραπείες', 14], ['Ομάδες στήριξης γονέων', 9], ['Φροντίδα το Σαββατοκύριακο', 6]],
      plans: [
        { n: 'Πλοηγός', f: 'Το Pyxida στο site σας, για το πρώτο βήμα', m: '119', s: '2.400 €', w: '3.550 € + 135 €/μήνα', h: ['Εκπαίδευση στα έγγραφά σας', 'Οδηγός δικαιωμάτων και παροχών', 'Widget και QR για τα έντυπα'], x: ['Απαντήσεις μόνο από εγκεκριμένες πηγές', 'Πρωτόκολλο κρίσης, καμία ιατρική συμβουλή', 'AI Act, GDPR, προσβασιμότητα', 'Βασικά στατιστικά', '1 εκπαίδευση, παρακολούθηση 30 ημερών'] },
        { n: 'Πλοηγός Insights', f: 'Για συλλόγους ασθενών και ΜΚΟ με χορηγούς', m: '179', s: '2.900 €', w: '4.450 € + 255 €/μήνα', rec: true, h: ['Όλα του Πλοηγού', 'Viber ή Messenger, δεύτερη γλώσσα', 'Insights και μηνιαία αναφορά για χορηγούς'], x: ['Θέματα ερωτήσεων και τάσεις', 'Αναπάντητες ερωτήσεις ως ανάγκες', 'Ανάλυση διάθεσης και κρίσεων', 'Μηνιαίο τεστ ακρίβειας', '2 εκπαιδεύσεις, παρακολούθηση 90 ημερών'] },
        { n: 'Φροντίδα', f: 'Για δομές με ωφελούμενους κάθε μέρα', m: '249', s: '4.500 €', w: '6.900 € + 495 €/μήνα', h: ['Όλα του Πλοηγού Insights', 'CRM: φάκελοι, καταγραφή, λήξεις', 'Ενημερώσεις οικογενειών με έγκριση'], x: ['Κάρτα βάρδιας: αγωγή, αλλεργίες', 'Καταγραφή με κουμπιά ή φωνή', 'Δωρητές, εθελοντές, μαζικά μηνύματα', 'Μεταφορά δεδομένων έως 40 ατόμων', '3 εκπαιδεύσεις, 1 δια ζώσης'] },
      ],
    },
    med: {
      day: [
        ['08:00', 'Τέσσερις αναπάντητες κλήσεις από χθες βράδυ.', 'Τα ραντεβού έκλεισαν', ' μέσα στη νύχτα, στο Viber.'],
        ['09:00', 'Ο ασθενής γράφει ιστορικό στην αίθουσα αναμονής.', 'Το ερωτηματολόγιο ήρθε', ' συμπληρωμένο από χθες.'],
        ['12:00', 'Μια ακύρωση αφήνει κενό μισή ώρα.', 'Η λίστα αναμονής', ' το γέμισε.'],
        ['19:00', 'Οι ετήσιοι έλεγχοι ξεχνιούνται.', 'Το recall έφυγε', ' με σύνδεσμο για ραντεβού.'],
      ],
      A: ['Ραντεβού 24/7 σε Viber και site', 'Υπενθυμίσεις 48 και 2 ωρών', 'Οδηγίες προετοιμασίας εξετάσεων'],
      C: ['Καρτέλα ασθενούς με ιστορικό', 'Follow-up και recall', 'Δουλεύει δίπλα στο πρόγραμμα ιατρείου σας'],
      th: [['Ραντεβού και διαθεσιμότητα', 38], ['Τιμές και ΕΟΠΥΥ', 21], ['Προετοιμασία εξετάσεων', 16], ['Αποτελέσματα', 14], ['Επανάληψη συνταγής', 11]],
      nd: [['Ραντεβού Σάββατο πρωί', 22], ['Τηλεϊατρική', 11], ['Αγγλικά για επισκέπτες', 7]],
      plans: [
        { n: 'Ιατρείο', f: 'Για τον γιατρό που δεν θέλει να χάνει τηλέφωνα', m: '129', s: '390 € · 0 € με ετήσια προπληρωμή', w: '3.300 € + 220 €/μήνα', h: ['Ραντεβού 24/7 σε Viber ή WhatsApp και site', 'Υπενθυμίσεις και οδηγίες εξετάσεων', 'Αίτημα κριτικής Google'], x: ['Απαντήσεις για υπηρεσίες, τιμές, ΕΟΠΥΥ', 'Σημάδια κινδύνου → 166 / 112', 'Λίστα επανάληψης συνταγής', 'Καρτέλα ασθενούς', 'Έτοιμο σε 5 εργάσιμες'] },
        { n: 'Κλινική', f: 'Για πολυϊατρεία και διαγνωστικά κέντρα', m: '290', s: '2.500 €', w: '6.900 € + 545 €/μήνα', rec: true, h: ['Όλα του Ιατρείου', 'Πολλοί γιατροί και αίθουσες', 'Follow-up, recall, κάλυψη ακυρώσεων'], x: ['Ερωτηματολόγιο πριν την επίσκεψη', 'Επανενεργοποίηση ασθενών', 'Μαζικά μηνύματα', 'Insights: ζήτηση, απουσίες, κενά', '2 εκπαιδεύσεις, παρακολούθηση 90 ημερών'] },
        { n: 'Κλινική Global', f: 'Για ιατρικό τουρισμό και πολλά σημεία', m: 'από 590', s: 'από 4.500 €', w: '', h: ['Όλα της Κλινικής', '3+ γλώσσες', 'Διεθνή αιτήματα, από την ερώτηση ως το follow-up'], x: ['Σύνδεση με το πρόγραμμα ιατρείου', 'Σύνδεση με ΗΔΥΚΑ μόλις πιστοποιηθεί', 'Πολλά σημεία, μία εικόνα', 'Δια ζώσης εκπαίδευση'] },
      ],
    },
  },
  en: {
    ngo: {
      day: [
        ['08:00', 'The shift starts by digging through notebooks.', 'The shift handover is ready', ' on one screen.'],
        ['10:30', 'Three calls: "how is she?". Work stops.', 'Pyxida answers', ' from the approved summary.'],
        ['16:00', 'A disability certificate expired and nobody noticed.', 'Reminders 60, 30 and 7 days ahead.', ''],
        ['18:00', 'The funder report: two evenings in Excel.', 'The monthly report', ' builds itself.'],
      ],
      A: ['Rights and benefits guidance', 'Sign-ups, donations, volunteering', 'Crisis protocol'],
      C: ['Case files and one-minute logging', 'Expiries and reminders', 'Family updates with approval'],
      th: [['Disability certification', 31], ['Welfare benefits', 22], ['Appointments and hospitals', 17], ['Psychological support', 12], ['Donations and volunteering', 8]],
      nd: [['Transport to therapy', 14], ['Parent support groups', 9], ['Weekend care', 6]],
      plans: [
        { n: 'Navigator', f: 'Pyxida on your site, as a first step', m: '119', s: '€2,400', w: '€3,550 + €135/month', h: ['Trained on your documents', 'Rights and benefits guide', 'Widget and QR for print'], x: ['Answers only from approved sources', 'Crisis protocol, no medical advice', 'AI Act, GDPR, accessibility', 'Basic statistics', '1 training, 30-day follow-up'] },
        { n: 'Navigator Insights', f: 'For patient associations and funded NGOs', m: '179', s: '€2,900', w: '€4,450 + €255/month', rec: true, h: ['Everything in Navigator', 'Viber or Messenger, second language', 'Insights and a monthly funder report'], x: ['Question themes and trends', 'Unanswered questions as needs', 'Sentiment and crisis analysis', 'Monthly accuracy test', '2 trainings, 90-day follow-up'] },
        { n: 'Care', f: 'For services with daily beneficiaries', m: '249', s: '€4,500', w: '€6,900 + €495/month', h: ['Everything in Navigator Insights', 'CRM: case files, logging, expiries', 'Family updates with approval'], x: ['Shift card: medication, allergies', 'Log by tap or voice', 'Donors, volunteers, bulk messages', 'Data migration for up to 40 people', '3 trainings, 1 on site'] },
      ],
    },
    med: {
      day: [
        ['08:00', 'Four missed calls from last night.', 'Appointments were booked', ' overnight, on Viber.'],
        ['09:00', 'The patient fills in history in the waiting room.', 'The intake form arrived', ' completed yesterday.'],
        ['12:00', 'A cancellation leaves a 30-minute gap.', 'The waiting list', ' filled it.'],
        ['19:00', 'Annual check-ups get forgotten.', 'The recall went out', ' with a booking link.'],
      ],
      A: ['24/7 booking on Viber and site', 'Reminders 48 and 2 hours ahead', 'Exam preparation instructions'],
      C: ['Patient card with history', 'Follow-up and recall', 'Works next to your practice software'],
      th: [['Appointments and availability', 38], ['Prices and insurance', 21], ['Exam preparation', 16], ['Results', 14], ['Repeat prescriptions', 11]],
      nd: [['Saturday morning slots', 22], ['Telemedicine', 11], ['English for visitors', 7]],
      plans: [
        { n: 'Practice', f: 'For the doctor who doesn\'t want to miss calls', m: '129', s: '€390 · €0 with annual prepay', w: '€3,300 + €220/month', h: ['24/7 booking on Viber or WhatsApp and site', 'Reminders and exam instructions', 'Google review request'], x: ['Answers on services, prices, insurance', 'Red flags → emergency numbers', 'Repeat-prescription list', 'Patient card', 'Live in 5 working days'] },
        { n: 'Clinic', f: 'For polyclinics and diagnostic centres', m: '290', s: '€2,500', w: '€6,900 + €545/month', rec: true, h: ['Everything in Practice', 'Multiple doctors and rooms', 'Follow-up, recall, cancellation fill'], x: ['Pre-visit questionnaire', 'Patient reactivation', 'Bulk messages', 'Insights: demand, no-shows, gaps', '2 trainings, 90-day follow-up'] },
        { n: 'Clinic Global', f: 'For medical tourism and multiple sites', m: 'from 590', s: 'from €4,500', w: '', h: ['Everything in Clinic', '3+ languages', 'International requests, from question to follow-up'], x: ['Practice software integration', 'National e-health record link once certified', 'Many sites, one view', 'On-site training'] },
      ],
    },
  },
};
