// /flow, Oct 2026 v3: the three parts of fλow, their live demos, the time that returns,
// the value equation by part, and «build your fλow» (which replaces fixed packages).

export const threeContent = {
  el: {
    layers: {
      title: 'Λόγος, Πράξη και Καταγραφή, σε μία ροή',
      lead: 'Τρία εργαλεία που δουλεύουν και μόνα τους. Μαζί, το ένα ξέρει ό,τι κάνει το άλλο: ό,τι ειπώθηκε γίνεται πράξη, κι ό,τι έγινε καταγράφεται.',
      toggle: ['Χωριστά', 'Μαζί'],
      toggleAria: 'Δείτε τα τρία μέρη χωριστά ή μαζί',
      parts: {
        dialogos: {
          word: 'Λόγος', line: 'Μιλά με τους ανθρώπους σας.',
          who: 'Για ασθενείς, ωφελούμενους, μέλη, οικογένειες.',
          items: ['Απαντά 24/7 στο site, στο Viber και στο WhatsApp', 'Μόνο από τις δικές σας εγκεκριμένες πηγές', 'Λέει «δεν ξέρω» και φωνάζει άνθρωπο όταν χρειάζεται', 'Καταλαβαίνει Greeklish και πολλές γλώσσες'],
        },
        praxis: {
          word: 'Πράξη', line: 'Κάνει τη δουλειά να προχωρά.',
          who: 'Για την ομάδα σας: εργαζόμενους, γραμματεία, εθελοντές.',
          items: ['Μητρώο μελών, φάκελοι ωφελουμένων ή καρτέλες ασθενών', 'Εργασίες ανά άνθρωπο, με προθεσμίες', 'Πρωτόκολλο με αυτόματη αρίθμηση', 'Ενέργειες με έγκριση: επιβεβαίωση ραντεβού, ενημέρωση βάρδιας', 'Σάρωση εγγράφων (OCR) στον φάκελο'],
        },
        metron: {
          word: 'Καταγραφή', line: 'Καταγράφει ό,τι συμβαίνει.',
          who: 'Για τη διοίκηση, τους χορηγούς, τις προτάσεις χρηματοδότησης.',
          items: ['Στατιστικά επικοινωνίας, σαν τηλεφωνικό κέντρο', 'Τι ρωτούν και τι λείπει, κάθε μήνα', 'Κοινωνικός αντίκτυπος, έτοιμος για χορηγούς', 'Τεστ ακρίβειας κάθε μήνα'],
        },
      },
      joint: {
        title: 'Μαζί, γίνονται μία ροή',
        items: ['Μια ερώτηση στο DialogosAI γίνεται ραντεβού στο PraxisAI', 'Κάθε επαφή και κάθε ενέργεια καταγράφεται στο MetronAI', 'Η αναφορά για τον χορηγό φτιάχνεται μόνη της', 'Τίποτα δεν φεύγει χωρίς έγκριση ανθρώπου'],
      },
      alone: 'Κάθε μέρος δουλεύει και μόνο του. Ξεκινάτε από ένα και προσθέτετε τα άλλα όταν είστε έτοιμοι.',
    },
    demos: {
      dialogos: { n: '01', word: 'Λόγος', title: 'Μια συζήτηση με το DialogosAI', lead: 'Διαλέξτε μια ερώτηση. Δείτε την απάντηση, την πηγή της, και τι γίνεται πίσω της στο PraxisAI και στο MetronAI.' },
      praxis: { n: '02', word: 'Πράξη', title: 'Το PraxisAI, ζωντανά', lead: 'Ένα CRM που δεν περιμένει να το γεμίσετε: προτείνει, εκτελεί και κρατά πρωτόκολλο. Πατήστε, δοκιμάστε, προσθέστε ενότητες.' },
      metron: { n: '03', word: 'Καταγραφή', title: 'Ό,τι ακούει, το θυμάται', lead: { ngo: 'Το MetronAI καταγράφει κάθε επαφή. Κάθε μήνα βλέπετε τι ρωτούν οι άνθρωποί σας και τι μένει αναπάντητο. Το δίνετε όπως είναι στους χορηγούς σας.', med: 'Το MetronAI καταγράφει κάθε επαφή. Κάθε μήνα βλέπετε τι ζητούν οι ασθενείς σας, τι χάνεται εκτός ωραρίου και πού μένουν κενά στο πρόγραμμα.' } },
      edition: { aria: 'Τύπος οργανισμού', ngo: 'ΜΚΟ και δομές', med: 'Ιατρεία και κλινικές' },
    },
    time: {
      title: 'Ο χρόνος που επιστρέφει',
      lead: 'Δεν μετράμε την ησυχία. Μετράμε τον χρόνο που γυρίζει στους ανθρώπους σας, και τι γίνεται αυτός ο χρόνος.',
      team: { ngo: 'Άνθρωποι στην ομάδα', med: 'Άνθρωποι στη γραμματεία' },
      doctors: 'Γιατροί',
      calls: { ngo: 'Τηλέφωνα και μηνύματα τη μέρα', med: 'Κλήσεις τη μέρα' },
      repeat: 'Πόσα είναι ίδιες ερωτήσεις',
      missed: 'Αναπάντητες κλήσεις τη μέρα',
      teamCap: { ngo: 'Η ομάδα σας', med: 'Το ιατρείο σας' },
      today: 'Σήμερα, κάθε μέρα',
      todayLine: (m) => `≈ ${m} λεπτά ο καθένας σε τηλέφωνα, χαρτιά και υπενθυμίσεις`,
      back: 'γυρίζουν πίσω',
      month: 'Κάθε μήνα',
      hoursMonth: 'ώρες πίσω στην ομάδα',
      byPart: { dialogos: 'απαντήσεις που δεν χρειάζεται να δώσετε', praxis: 'καταγραφή, προθεσμίες, πρωτόκολλο', metron: 'αναφορές που φτιάχνονται μόνες' },
      year: 'Σε έναν χρόνο',
      days: 'εργάσιμες μέρες',
      daysLine: 'πίσω στη φροντίδα',
      appts: (n) => `+ ${n} ραντεβού τον μήνα από κλήσεις που σήμερα χάνονται`,
      forWhat: 'Χρόνος για',
      moments: {
        ngo: ['ένα τηλεφώνημα που δεν βιάζεται', 'μια βόλτα με τον Νίκο στον κήπο', 'μια οικογένεια που ακούστηκε', 'να φύγει η ομάδα στην ώρα της'],
        med: ['έναν ασθενή που τον ακούτε χωρίς βιασύνη', 'ένα διάλειμμα ανάμεσα στα ραντεβού', 'μια εξήγηση που δεν κόβεται στη μέση', 'να κλείσει το ιατρείο στην ώρα του'],
      },
      euroToggle: 'Δείτε το και σε ευρώ',
      rate: 'Κόστος μιας ώρας εργασίας',
      fee: 'Μέση αξία ενός ραντεβού',
      worth: 'Η αξία αυτού του χρόνου, τον χρόνο',
      euroNote: 'Αν η ομάδα σας είναι εθελοντές, μείνετε στις ώρες: αυτές μετράνε.',
      note: 'Εκτίμηση: 4 λεπτά ανά επαναλαμβανόμενη ερώτηση, 22 εργάσιμες τον μήνα, 8 ώρες τη μέρα. Δεν είναι υπόσχεση· το μετράμε μαζί σας στο MetronAI.',
      months: ['Ι', 'Φ', 'Μ', 'Α', 'Μ', 'Ι', 'Ι', 'Α', 'Σ', 'Ο', 'Ν', 'Δ'],
    },
    eq: {
      title: 'Γιατί αξίζει περισσότερο απ᾽ όσο κοστίζει',
      top: [
        ['Το αποτέλεσμα', 'Μια ήσυχη μέρα: η ομάδα φεύγει στην ώρα της, οι άνθρωποί σας ησυχάζουν.', 'flow'],
        ['Η βεβαιότητα', 'Το MetronAI σάς δείχνει κάθε μήνα τι άλλαξε, σε αριθμούς. Εγγύηση 90% ακρίβειας, αλλιώς δεν πληρώνετε.', 'metron'],
      ],
      bottom: [
        ['Ο χρόνος αναμονής', 'Το DialogosAI απαντά από τις πρώτες 48 ώρες, μέρα και νύχτα.', 'dialogos'],
        ['Ο κόπος σας', 'Το PraxisAI τα κάνει μόνο του: επιβεβαιώνει ραντεβού, κρατά πρωτόκολλο, θυμίζει προθεσμίες.', 'praxis'],
      ],
      caption: 'Η αξία μεγαλώνει όταν τα πάνω ανεβαίνουν και τα κάτω μικραίνουν.',
    },
    build: {
      title: 'Φτιάξτε το δικό σας fλow',
      lead: 'Δεν υπάρχουν έτοιμα πακέτα, γιατί κανένας οργανισμός δεν είναι ίδιος με τον άλλον. Διαλέξτε τα μέρη που χρειάζεστε. Μαζί κάνουν περισσότερα.',
      on: 'Μέσα', off: 'Προσθήκη',
      chosen: (n) => (n === 1 ? 'μέρος στο fλow σας' : 'μέρη στο fλow σας'),
      offerByEmail: 'Η προσφορά σας έρχεται σε PDF στο email σας',
      medNote: 'Στα ιατρεία, το fλow έρχεται ολόκληρο από την πρώτη μέρα. Η προσφορά σας έρχεται σε PDF στο email σας, φτιαγμένη για το ιατρείο σας.',
      cta: 'Συνεχίστε: σχεδιάστε το αναλυτικά',
      hint: 'Στο επόμενο βήμα διαλέγετε δυνατότητες, προσθέτετε τα δικά σας και λαμβάνετε την προσφορά σας στο email σας, μέσα σε μία εργάσιμη.',
      need: 'Διαλέξτε τουλάχιστον ένα μέρος.',
      guarantee: {
        ngo: ['Ξεκινήστε χωρίς ρίσκο', 'Με δοκιμαστική περίοδο, με τα δικά σας δεδομένα, και εγγύηση ακρίβειας: αν δεν απαντά σωστά στο 90% των ερωτήσεων που συμφωνήσαμε, η συνδρομή είναι δωρεάν ώσπου να το πετύχει. Όλοι οι όροι είναι στην προσφορά σας.'],
        med: ['Live σε 48 ώρες, αλλιώς δωρεάν', 'Τεστ αποδοχής με 50 πραγματικές ερωτήσεις, μπροστά σας: αν δεν φτάσει το 90% ακρίβεια, δεν πληρώνετε. Όλοι οι όροι είναι στην προσφορά σας.'],
      },
      note: 'Η προσφορά σας φτιάχνεται από όσα διαλέγετε και έρχεται σε PDF στο email σας.',
    },
  },

  en: {
    layers: {
      title: 'Dialogue, action and record, in one flow',
      lead: 'Three tools that also work on their own. Together, each knows what the others do: what was said becomes action, and what was done is recorded.',
      toggle: ['Separately', 'Together'],
      toggleAria: 'See the three parts separately or together',
      parts: {
        dialogos: {
          word: 'Logos', line: 'Talks with your people.',
          who: 'For patients, beneficiaries, members, families.',
          items: ['Answers 24/7 on your site, Viber and WhatsApp', 'Only from your own approved sources', 'Says "I don\'t know" and calls a person when needed', 'Understands Greeklish and many languages'],
        },
        praxis: {
          word: 'Praxis', line: 'Keeps the work moving.',
          who: 'For your team: staff, front desk, volunteers.',
          items: ['Member registry, beneficiary files or patient records', 'Tasks per person, with deadlines', 'A protocol book with automatic numbers', 'Actions with approval: confirming appointments, shift handovers', 'Document scanning (OCR) into the file'],
        },
        metron: {
          word: 'Record', line: 'Records what happens.',
          who: 'For management, sponsors and funding proposals.',
          items: ['Communication statistics, like a call centre', 'What people ask and what is missing, monthly', 'Social impact, ready for sponsors', 'A monthly accuracy test'],
        },
      },
      joint: {
        title: 'Together, they become one flow',
        items: ['A question to DialogosAI becomes an appointment in PraxisAI', 'Every contact and every action is recorded in MetronAI', 'The sponsor report writes itself', 'Nothing goes out without a person\'s approval'],
      },
      alone: 'Each part also works on its own. Start with one and add the others when you are ready.',
    },
    demos: {
      dialogos: { n: '01', word: 'Logos', title: 'A conversation with DialogosAI', lead: 'Pick a question. See the answer, its source, and what happens behind it in PraxisAI and MetronAI.' },
      praxis: { n: '02', word: 'Praxis', title: 'PraxisAI, live', lead: 'A CRM that doesn\'t wait for you to fill it: it proposes, acts and keeps a protocol book. Click, try, add modules.' },
      metron: { n: '03', word: 'Record', title: 'What it hears, it remembers', lead: { ngo: 'MetronAI records every contact. Each month you see what your people ask and what stays unanswered, and hand it to your sponsors as it is.', med: 'MetronAI records every contact. Each month you see what your patients ask for, what is lost after hours, and where your schedule has gaps.' } },
      edition: { aria: 'Type of organisation', ngo: 'NGOs and care services', med: 'Practices and clinics' },
    },
    time: {
      title: 'The time that comes back',
      lead: 'We don\'t measure calm. We measure the time that returns to your people, and what that time becomes.',
      team: { ngo: 'People on the team', med: 'People at the front desk' },
      doctors: 'Doctors',
      calls: { ngo: 'Calls and messages a day', med: 'Calls a day' },
      repeat: 'How many are the same questions',
      missed: 'Missed calls a day',
      teamCap: { ngo: 'Your team', med: 'Your practice' },
      today: 'Today, every day',
      todayLine: (m) => `≈ ${m} minutes each on calls, paperwork and reminders`,
      back: 'come back',
      month: 'Every month',
      hoursMonth: 'hours back to the team',
      byPart: { dialogos: 'answers you no longer have to give', praxis: 'records, deadlines, protocol book', metron: 'reports that write themselves' },
      year: 'In one year',
      days: 'working days',
      daysLine: 'back to care',
      appts: (n) => `+ ${n} appointments a month from calls lost today`,
      forWhat: 'Time for',
      moments: {
        ngo: ['a phone call that isn\'t rushed', 'a walk with Nikos in the garden', 'a family that felt heard', 'the team leaving on time'],
        med: ['a patient you listen to without hurrying', 'a break between appointments', 'an explanation that isn\'t cut short', 'closing the practice on time'],
      },
      euroToggle: 'Show it in euros too',
      rate: 'Cost of one working hour',
      fee: 'Average value of an appointment',
      worth: 'Value of this time, per year',
      euroNote: 'If your team are volunteers, stay with the hours: they are what counts.',
      note: 'Estimate: 4 minutes per repeated question, 22 working days a month, 8-hour days. Not a promise; we measure it with you in MetronAI.',
      months: ['J', 'F', 'M', 'A', 'M', 'J', 'J', 'A', 'S', 'O', 'N', 'D'],
    },
    eq: {
      title: 'Why it is worth more than it costs',
      top: [
        ['The outcome', 'A quiet day: the team leaves on time, your people are reassured.', 'flow'],
        ['The certainty', 'MetronAI shows you every month what changed, in numbers. 90% accuracy guaranteed, or you don\'t pay.', 'metron'],
      ],
      bottom: [
        ['The waiting', 'DialogosAI answers from the first 48 hours, day and night.', 'dialogos'],
        ['Your effort', 'PraxisAI does it on its own: confirms appointments, keeps the protocol book, reminds you of deadlines.', 'praxis'],
      ],
      caption: 'Value grows when the top goes up and the bottom shrinks.',
    },
    build: {
      title: 'Build your own fλow',
      lead: 'There are no fixed packages, because no two organisations are alike. Choose the parts you need. Together they do more.',
      on: 'In', off: 'Add',
      chosen: (n) => (n === 1 ? 'part in your fλow' : 'parts in your fλow'),
      offerByEmail: 'Your offer arrives as a PDF in your inbox',
      medNote: 'For practices, fλow comes whole from day one. Your offer arrives as a PDF in your inbox, made for your practice.',
      cta: 'Continue: design it in detail',
      hint: 'Next you choose features, add your own, and receive your offer by email within one working day.',
      need: 'Choose at least one part.',
      guarantee: {
        ngo: ['Start with no risk', 'With a trial period on your own data, and an accuracy guarantee: if it doesn\'t answer 90% of the agreed questions correctly, the subscription is free until it does. All the terms are in your offer.'],
        med: ['Live in 48 hours, or free', 'An acceptance test with 50 real questions, in front of you: if it doesn\'t reach 90% accuracy, you don\'t pay. All the terms are in your offer.'],
      },
      note: 'Your offer is built from what you choose and arrives as a PDF in your inbox.',
    },
  },
};
